/*
AskNews API

Testing ByokAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package asknews

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/emergentmethods/asknews-go-sdk"
)

func Test_asknews_ByokAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ByokAPIService DeleteByokKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var provider string

		httpRes, err := apiClient.ByokAPI.DeleteByokKey(context.Background(), provider).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ByokAPIService GetByokKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var provider string

		resp, httpRes, err := apiClient.ByokAPI.GetByokKey(context.Background(), provider).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ByokAPIService UpsertByokKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var provider string

		resp, httpRes, err := apiClient.ByokAPI.UpsertByokKey(context.Background(), provider).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
