/*
AskNews API

Testing StoriesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package asknews

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/emergentmethods/asknews-go-sdk"
)

func Test_asknews_StoriesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test StoriesAPIService GetStories", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.StoriesAPI.GetStories(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StoriesAPIService GetStory", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storyId string

		resp, httpRes, err := apiClient.StoriesAPI.GetStory(context.Background(), storyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
