/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.22
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the AbcAPIErrorModel53 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AbcAPIErrorModel53{}

// AbcAPIErrorModel53 struct for AbcAPIErrorModel53
type AbcAPIErrorModel53 struct {
	Code int32 `json:"code"`
	Detail string `json:"detail"`
	AdditionalProperties map[string]interface{}
}

type _AbcAPIErrorModel53 AbcAPIErrorModel53

// NewAbcAPIErrorModel53 instantiates a new AbcAPIErrorModel53 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAbcAPIErrorModel53(code int32, detail string) *AbcAPIErrorModel53 {
	this := AbcAPIErrorModel53{}
	this.Code = code
	this.Detail = detail
	return &this
}

// NewAbcAPIErrorModel53WithDefaults instantiates a new AbcAPIErrorModel53 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAbcAPIErrorModel53WithDefaults() *AbcAPIErrorModel53 {
	this := AbcAPIErrorModel53{}
	return &this
}

// GetCode returns the Code field value
func (o *AbcAPIErrorModel53) GetCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *AbcAPIErrorModel53) GetCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *AbcAPIErrorModel53) SetCode(v int32) {
	o.Code = v
}

// GetDetail returns the Detail field value
func (o *AbcAPIErrorModel53) GetDetail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Detail
}

// GetDetailOk returns a tuple with the Detail field value
// and a boolean to check if the value has been set.
func (o *AbcAPIErrorModel53) GetDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Detail, true
}

// SetDetail sets field value
func (o *AbcAPIErrorModel53) SetDetail(v string) {
	o.Detail = v
}

func (o AbcAPIErrorModel53) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AbcAPIErrorModel53) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["detail"] = o.Detail

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AbcAPIErrorModel53) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"detail",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAbcAPIErrorModel53 := _AbcAPIErrorModel53{}

	err = json.Unmarshal(data, &varAbcAPIErrorModel53)

	if err != nil {
		return err
	}

	*o = AbcAPIErrorModel53(varAbcAPIErrorModel53)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "detail")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAbcAPIErrorModel53 struct {
	value *AbcAPIErrorModel53
	isSet bool
}

func (v NullableAbcAPIErrorModel53) Get() *AbcAPIErrorModel53 {
	return v.value
}

func (v *NullableAbcAPIErrorModel53) Set(val *AbcAPIErrorModel53) {
	v.value = val
	v.isSet = true
}

func (v NullableAbcAPIErrorModel53) IsSet() bool {
	return v.isSet
}

func (v *NullableAbcAPIErrorModel53) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAbcAPIErrorModel53(val *AbcAPIErrorModel53) *NullableAbcAPIErrorModel53 {
	return &NullableAbcAPIErrorModel53{value: val, isSet: true}
}

func (v NullableAbcAPIErrorModel53) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAbcAPIErrorModel53) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


