/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.66
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// DeepNews200Response - struct for DeepNews200Response
type DeepNews200Response struct {
	CreateDeepNewsResponseStreamChunk1 *CreateDeepNewsResponseStreamChunk1
	CreateDeepNewsResponseStreamChunkV21 *CreateDeepNewsResponseStreamChunkV21
	CreateDeepNewsResponseStreamSource1 *CreateDeepNewsResponseStreamSource1
}

// CreateDeepNewsResponseStreamChunk1AsDeepNews200Response is a convenience function that returns CreateDeepNewsResponseStreamChunk1 wrapped in DeepNews200Response
func CreateDeepNewsResponseStreamChunk1AsDeepNews200Response(v *CreateDeepNewsResponseStreamChunk1) DeepNews200Response {
	return DeepNews200Response{
		CreateDeepNewsResponseStreamChunk1: v,
	}
}

// CreateDeepNewsResponseStreamChunkV21AsDeepNews200Response is a convenience function that returns CreateDeepNewsResponseStreamChunkV21 wrapped in DeepNews200Response
func CreateDeepNewsResponseStreamChunkV21AsDeepNews200Response(v *CreateDeepNewsResponseStreamChunkV21) DeepNews200Response {
	return DeepNews200Response{
		CreateDeepNewsResponseStreamChunkV21: v,
	}
}

// CreateDeepNewsResponseStreamSource1AsDeepNews200Response is a convenience function that returns CreateDeepNewsResponseStreamSource1 wrapped in DeepNews200Response
func CreateDeepNewsResponseStreamSource1AsDeepNews200Response(v *CreateDeepNewsResponseStreamSource1) DeepNews200Response {
	return DeepNews200Response{
		CreateDeepNewsResponseStreamSource1: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *DeepNews200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CreateDeepNewsResponseStreamChunk1
	err = newStrictDecoder(data).Decode(&dst.CreateDeepNewsResponseStreamChunk1)
	if err == nil {
		jsonCreateDeepNewsResponseStreamChunk1, _ := json.Marshal(dst.CreateDeepNewsResponseStreamChunk1)
		if string(jsonCreateDeepNewsResponseStreamChunk1) == "{}" { // empty struct
			dst.CreateDeepNewsResponseStreamChunk1 = nil
		} else {
			if err = validator.Validate(dst.CreateDeepNewsResponseStreamChunk1); err != nil {
				dst.CreateDeepNewsResponseStreamChunk1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateDeepNewsResponseStreamChunk1 = nil
	}

	// try to unmarshal data into CreateDeepNewsResponseStreamChunkV21
	err = newStrictDecoder(data).Decode(&dst.CreateDeepNewsResponseStreamChunkV21)
	if err == nil {
		jsonCreateDeepNewsResponseStreamChunkV21, _ := json.Marshal(dst.CreateDeepNewsResponseStreamChunkV21)
		if string(jsonCreateDeepNewsResponseStreamChunkV21) == "{}" { // empty struct
			dst.CreateDeepNewsResponseStreamChunkV21 = nil
		} else {
			if err = validator.Validate(dst.CreateDeepNewsResponseStreamChunkV21); err != nil {
				dst.CreateDeepNewsResponseStreamChunkV21 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateDeepNewsResponseStreamChunkV21 = nil
	}

	// try to unmarshal data into CreateDeepNewsResponseStreamSource1
	err = newStrictDecoder(data).Decode(&dst.CreateDeepNewsResponseStreamSource1)
	if err == nil {
		jsonCreateDeepNewsResponseStreamSource1, _ := json.Marshal(dst.CreateDeepNewsResponseStreamSource1)
		if string(jsonCreateDeepNewsResponseStreamSource1) == "{}" { // empty struct
			dst.CreateDeepNewsResponseStreamSource1 = nil
		} else {
			if err = validator.Validate(dst.CreateDeepNewsResponseStreamSource1); err != nil {
				dst.CreateDeepNewsResponseStreamSource1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateDeepNewsResponseStreamSource1 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CreateDeepNewsResponseStreamChunk1 = nil
		dst.CreateDeepNewsResponseStreamChunkV21 = nil
		dst.CreateDeepNewsResponseStreamSource1 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(DeepNews200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(DeepNews200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src DeepNews200Response) MarshalJSON() ([]byte, error) {
	if src.CreateDeepNewsResponseStreamChunk1 != nil {
		return json.Marshal(&src.CreateDeepNewsResponseStreamChunk1)
	}

	if src.CreateDeepNewsResponseStreamChunkV21 != nil {
		return json.Marshal(&src.CreateDeepNewsResponseStreamChunkV21)
	}

	if src.CreateDeepNewsResponseStreamSource1 != nil {
		return json.Marshal(&src.CreateDeepNewsResponseStreamSource1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *DeepNews200Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CreateDeepNewsResponseStreamChunk1 != nil {
		return obj.CreateDeepNewsResponseStreamChunk1
	}

	if obj.CreateDeepNewsResponseStreamChunkV21 != nil {
		return obj.CreateDeepNewsResponseStreamChunkV21
	}

	if obj.CreateDeepNewsResponseStreamSource1 != nil {
		return obj.CreateDeepNewsResponseStreamSource1
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj DeepNews200Response) GetActualInstanceValue() (interface{}) {
	if obj.CreateDeepNewsResponseStreamChunk1 != nil {
		return *obj.CreateDeepNewsResponseStreamChunk1
	}

	if obj.CreateDeepNewsResponseStreamChunkV21 != nil {
		return *obj.CreateDeepNewsResponseStreamChunkV21
	}

	if obj.CreateDeepNewsResponseStreamSource1 != nil {
		return *obj.CreateDeepNewsResponseStreamSource1
	}

	// all schemas are nil
	return nil
}

type NullableDeepNews200Response struct {
	value *DeepNews200Response
	isSet bool
}

func (v NullableDeepNews200Response) Get() *DeepNews200Response {
	return v.value
}

func (v *NullableDeepNews200Response) Set(val *DeepNews200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDeepNews200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDeepNews200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeepNews200Response(val *DeepNews200Response) *NullableDeepNews200Response {
	return &NullableDeepNews200Response{value: val, isSet: true}
}

func (v NullableDeepNews200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeepNews200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


