/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.22
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedResponseAlertResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedResponseAlertResponse{}

// PaginatedResponseAlertResponse struct for PaginatedResponseAlertResponse
type PaginatedResponseAlertResponse struct {
	Items []AlertResponse `json:"items"`
	Count int32 `json:"count"`
	NextPage NullableInt32 `json:"next_page"`
	PreviousPage NullableInt32 `json:"previous_page"`
	AdditionalProperties map[string]interface{}
}

type _PaginatedResponseAlertResponse PaginatedResponseAlertResponse

// NewPaginatedResponseAlertResponse instantiates a new PaginatedResponseAlertResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedResponseAlertResponse(items []AlertResponse, count int32, nextPage NullableInt32, previousPage NullableInt32) *PaginatedResponseAlertResponse {
	this := PaginatedResponseAlertResponse{}
	this.Items = items
	this.Count = count
	this.NextPage = nextPage
	this.PreviousPage = previousPage
	return &this
}

// NewPaginatedResponseAlertResponseWithDefaults instantiates a new PaginatedResponseAlertResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedResponseAlertResponseWithDefaults() *PaginatedResponseAlertResponse {
	this := PaginatedResponseAlertResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *PaginatedResponseAlertResponse) GetItems() []AlertResponse {
	if o == nil {
		var ret []AlertResponse
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseAlertResponse) GetItemsOk() ([]AlertResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *PaginatedResponseAlertResponse) SetItems(v []AlertResponse) {
	o.Items = v
}

// GetCount returns the Count field value
func (o *PaginatedResponseAlertResponse) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseAlertResponse) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *PaginatedResponseAlertResponse) SetCount(v int32) {
	o.Count = v
}

// GetNextPage returns the NextPage field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *PaginatedResponseAlertResponse) GetNextPage() int32 {
	if o == nil || o.NextPage.Get() == nil {
		var ret int32
		return ret
	}

	return *o.NextPage.Get()
}

// GetNextPageOk returns a tuple with the NextPage field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedResponseAlertResponse) GetNextPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextPage.Get(), o.NextPage.IsSet()
}

// SetNextPage sets field value
func (o *PaginatedResponseAlertResponse) SetNextPage(v int32) {
	o.NextPage.Set(&v)
}

// GetPreviousPage returns the PreviousPage field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *PaginatedResponseAlertResponse) GetPreviousPage() int32 {
	if o == nil || o.PreviousPage.Get() == nil {
		var ret int32
		return ret
	}

	return *o.PreviousPage.Get()
}

// GetPreviousPageOk returns a tuple with the PreviousPage field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedResponseAlertResponse) GetPreviousPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PreviousPage.Get(), o.PreviousPage.IsSet()
}

// SetPreviousPage sets field value
func (o *PaginatedResponseAlertResponse) SetPreviousPage(v int32) {
	o.PreviousPage.Set(&v)
}

func (o PaginatedResponseAlertResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedResponseAlertResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["count"] = o.Count
	toSerialize["next_page"] = o.NextPage.Get()
	toSerialize["previous_page"] = o.PreviousPage.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginatedResponseAlertResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"count",
		"next_page",
		"previous_page",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedResponseAlertResponse := _PaginatedResponseAlertResponse{}

	err = json.Unmarshal(data, &varPaginatedResponseAlertResponse)

	if err != nil {
		return err
	}

	*o = PaginatedResponseAlertResponse(varPaginatedResponseAlertResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		delete(additionalProperties, "count")
		delete(additionalProperties, "next_page")
		delete(additionalProperties, "previous_page")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginatedResponseAlertResponse struct {
	value *PaginatedResponseAlertResponse
	isSet bool
}

func (v NullablePaginatedResponseAlertResponse) Get() *PaginatedResponseAlertResponse {
	return v.value
}

func (v *NullablePaginatedResponseAlertResponse) Set(val *PaginatedResponseAlertResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedResponseAlertResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedResponseAlertResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedResponseAlertResponse(val *PaginatedResponseAlertResponse) *NullablePaginatedResponseAlertResponse {
	return &NullablePaginatedResponseAlertResponse{value: val, isSet: true}
}

func (v NullablePaginatedResponseAlertResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedResponseAlertResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


