/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.31.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the DomainMetricsDayItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainMetricsDayItem{}

// DomainMetricsDayItem struct for DomainMetricsDayItem
type DomainMetricsDayItem struct {
	Day string `json:"day"`
	Surfaces int32 `json:"surfaces"`
	Citations int32 `json:"citations"`
	FullText int32 `json:"full_text"`
	Grounded *int32 `json:"grounded,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DomainMetricsDayItem DomainMetricsDayItem

// NewDomainMetricsDayItem instantiates a new DomainMetricsDayItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainMetricsDayItem(day string, surfaces int32, citations int32, fullText int32) *DomainMetricsDayItem {
	this := DomainMetricsDayItem{}
	this.Day = day
	this.Surfaces = surfaces
	this.Citations = citations
	this.FullText = fullText
	var grounded int32 = 0
	this.Grounded = &grounded
	return &this
}

// NewDomainMetricsDayItemWithDefaults instantiates a new DomainMetricsDayItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainMetricsDayItemWithDefaults() *DomainMetricsDayItem {
	this := DomainMetricsDayItem{}
	var grounded int32 = 0
	this.Grounded = &grounded
	return &this
}

// GetDay returns the Day field value
func (o *DomainMetricsDayItem) GetDay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Day
}

// GetDayOk returns a tuple with the Day field value
// and a boolean to check if the value has been set.
func (o *DomainMetricsDayItem) GetDayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Day, true
}

// SetDay sets field value
func (o *DomainMetricsDayItem) SetDay(v string) {
	o.Day = v
}

// GetSurfaces returns the Surfaces field value
func (o *DomainMetricsDayItem) GetSurfaces() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Surfaces
}

// GetSurfacesOk returns a tuple with the Surfaces field value
// and a boolean to check if the value has been set.
func (o *DomainMetricsDayItem) GetSurfacesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Surfaces, true
}

// SetSurfaces sets field value
func (o *DomainMetricsDayItem) SetSurfaces(v int32) {
	o.Surfaces = v
}

// GetCitations returns the Citations field value
func (o *DomainMetricsDayItem) GetCitations() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Citations
}

// GetCitationsOk returns a tuple with the Citations field value
// and a boolean to check if the value has been set.
func (o *DomainMetricsDayItem) GetCitationsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Citations, true
}

// SetCitations sets field value
func (o *DomainMetricsDayItem) SetCitations(v int32) {
	o.Citations = v
}

// GetFullText returns the FullText field value
func (o *DomainMetricsDayItem) GetFullText() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FullText
}

// GetFullTextOk returns a tuple with the FullText field value
// and a boolean to check if the value has been set.
func (o *DomainMetricsDayItem) GetFullTextOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FullText, true
}

// SetFullText sets field value
func (o *DomainMetricsDayItem) SetFullText(v int32) {
	o.FullText = v
}

// GetGrounded returns the Grounded field value if set, zero value otherwise.
func (o *DomainMetricsDayItem) GetGrounded() int32 {
	if o == nil || IsNil(o.Grounded) {
		var ret int32
		return ret
	}
	return *o.Grounded
}

// GetGroundedOk returns a tuple with the Grounded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainMetricsDayItem) GetGroundedOk() (*int32, bool) {
	if o == nil || IsNil(o.Grounded) {
		return nil, false
	}
	return o.Grounded, true
}

// HasGrounded returns a boolean if a field has been set.
func (o *DomainMetricsDayItem) HasGrounded() bool {
	if o != nil && !IsNil(o.Grounded) {
		return true
	}

	return false
}

// SetGrounded gets a reference to the given int32 and assigns it to the Grounded field.
func (o *DomainMetricsDayItem) SetGrounded(v int32) {
	o.Grounded = &v
}

func (o DomainMetricsDayItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainMetricsDayItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["day"] = o.Day
	toSerialize["surfaces"] = o.Surfaces
	toSerialize["citations"] = o.Citations
	toSerialize["full_text"] = o.FullText
	if !IsNil(o.Grounded) {
		toSerialize["grounded"] = o.Grounded
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DomainMetricsDayItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"day",
		"surfaces",
		"citations",
		"full_text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainMetricsDayItem := _DomainMetricsDayItem{}

	err = json.Unmarshal(data, &varDomainMetricsDayItem)

	if err != nil {
		return err
	}

	*o = DomainMetricsDayItem(varDomainMetricsDayItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "day")
		delete(additionalProperties, "surfaces")
		delete(additionalProperties, "citations")
		delete(additionalProperties, "full_text")
		delete(additionalProperties, "grounded")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDomainMetricsDayItem struct {
	value *DomainMetricsDayItem
	isSet bool
}

func (v NullableDomainMetricsDayItem) Get() *DomainMetricsDayItem {
	return v.value
}

func (v *NullableDomainMetricsDayItem) Set(val *DomainMetricsDayItem) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainMetricsDayItem) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainMetricsDayItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainMetricsDayItem(val *DomainMetricsDayItem) *NullableDomainMetricsDayItem {
	return &NullableDomainMetricsDayItem{value: val, isSet: true}
}

func (v NullableDomainMetricsDayItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainMetricsDayItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


