/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.28
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateChatCompletionResponseStreamChoice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateChatCompletionResponseStreamChoice{}

// CreateChatCompletionResponseStreamChoice struct for CreateChatCompletionResponseStreamChoice
type CreateChatCompletionResponseStreamChoice struct {
	Index int32 `json:"index"`
	Delta CreateChatCompletionRequestMessage `json:"delta"`
	FinishReason NullableString `json:"finish_reason,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateChatCompletionResponseStreamChoice CreateChatCompletionResponseStreamChoice

// NewCreateChatCompletionResponseStreamChoice instantiates a new CreateChatCompletionResponseStreamChoice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateChatCompletionResponseStreamChoice(index int32, delta CreateChatCompletionRequestMessage) *CreateChatCompletionResponseStreamChoice {
	this := CreateChatCompletionResponseStreamChoice{}
	this.Index = index
	this.Delta = delta
	return &this
}

// NewCreateChatCompletionResponseStreamChoiceWithDefaults instantiates a new CreateChatCompletionResponseStreamChoice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateChatCompletionResponseStreamChoiceWithDefaults() *CreateChatCompletionResponseStreamChoice {
	this := CreateChatCompletionResponseStreamChoice{}
	return &this
}

// GetIndex returns the Index field value
func (o *CreateChatCompletionResponseStreamChoice) GetIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *CreateChatCompletionResponseStreamChoice) GetIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *CreateChatCompletionResponseStreamChoice) SetIndex(v int32) {
	o.Index = v
}

// GetDelta returns the Delta field value
func (o *CreateChatCompletionResponseStreamChoice) GetDelta() CreateChatCompletionRequestMessage {
	if o == nil {
		var ret CreateChatCompletionRequestMessage
		return ret
	}

	return o.Delta
}

// GetDeltaOk returns a tuple with the Delta field value
// and a boolean to check if the value has been set.
func (o *CreateChatCompletionResponseStreamChoice) GetDeltaOk() (*CreateChatCompletionRequestMessage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Delta, true
}

// SetDelta sets field value
func (o *CreateChatCompletionResponseStreamChoice) SetDelta(v CreateChatCompletionRequestMessage) {
	o.Delta = v
}

// GetFinishReason returns the FinishReason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateChatCompletionResponseStreamChoice) GetFinishReason() string {
	if o == nil || IsNil(o.FinishReason.Get()) {
		var ret string
		return ret
	}
	return *o.FinishReason.Get()
}

// GetFinishReasonOk returns a tuple with the FinishReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateChatCompletionResponseStreamChoice) GetFinishReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FinishReason.Get(), o.FinishReason.IsSet()
}

// HasFinishReason returns a boolean if a field has been set.
func (o *CreateChatCompletionResponseStreamChoice) HasFinishReason() bool {
	if o != nil && o.FinishReason.IsSet() {
		return true
	}

	return false
}

// SetFinishReason gets a reference to the given NullableString and assigns it to the FinishReason field.
func (o *CreateChatCompletionResponseStreamChoice) SetFinishReason(v string) {
	o.FinishReason.Set(&v)
}
// SetFinishReasonNil sets the value for FinishReason to be an explicit nil
func (o *CreateChatCompletionResponseStreamChoice) SetFinishReasonNil() {
	o.FinishReason.Set(nil)
}

// UnsetFinishReason ensures that no value is present for FinishReason, not even an explicit nil
func (o *CreateChatCompletionResponseStreamChoice) UnsetFinishReason() {
	o.FinishReason.Unset()
}

func (o CreateChatCompletionResponseStreamChoice) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateChatCompletionResponseStreamChoice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["index"] = o.Index
	toSerialize["delta"] = o.Delta
	if o.FinishReason.IsSet() {
		toSerialize["finish_reason"] = o.FinishReason.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateChatCompletionResponseStreamChoice) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index",
		"delta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateChatCompletionResponseStreamChoice := _CreateChatCompletionResponseStreamChoice{}

	err = json.Unmarshal(data, &varCreateChatCompletionResponseStreamChoice)

	if err != nil {
		return err
	}

	*o = CreateChatCompletionResponseStreamChoice(varCreateChatCompletionResponseStreamChoice)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "index")
		delete(additionalProperties, "delta")
		delete(additionalProperties, "finish_reason")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateChatCompletionResponseStreamChoice struct {
	value *CreateChatCompletionResponseStreamChoice
	isSet bool
}

func (v NullableCreateChatCompletionResponseStreamChoice) Get() *CreateChatCompletionResponseStreamChoice {
	return v.value
}

func (v *NullableCreateChatCompletionResponseStreamChoice) Set(val *CreateChatCompletionResponseStreamChoice) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateChatCompletionResponseStreamChoice) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateChatCompletionResponseStreamChoice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateChatCompletionResponseStreamChoice(val *CreateChatCompletionResponseStreamChoice) *NullableCreateChatCompletionResponseStreamChoice {
	return &NullableCreateChatCompletionResponseStreamChoice{value: val, isSet: true}
}

func (v NullableCreateChatCompletionResponseStreamChoice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateChatCompletionResponseStreamChoice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


