/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.27
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the RedditComment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RedditComment{}

// RedditComment struct for RedditComment
type RedditComment struct {
	Author string `json:"author"`
	Body string `json:"body"`
	Date time.Time `json:"date"`
	Upvotes int32 `json:"upvotes"`
	AdditionalProperties map[string]interface{}
}

type _RedditComment RedditComment

// NewRedditComment instantiates a new RedditComment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRedditComment(author string, body string, date time.Time, upvotes int32) *RedditComment {
	this := RedditComment{}
	this.Author = author
	this.Body = body
	this.Date = date
	this.Upvotes = upvotes
	return &this
}

// NewRedditCommentWithDefaults instantiates a new RedditComment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRedditCommentWithDefaults() *RedditComment {
	this := RedditComment{}
	return &this
}

// GetAuthor returns the Author field value
func (o *RedditComment) GetAuthor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Author
}

// GetAuthorOk returns a tuple with the Author field value
// and a boolean to check if the value has been set.
func (o *RedditComment) GetAuthorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Author, true
}

// SetAuthor sets field value
func (o *RedditComment) SetAuthor(v string) {
	o.Author = v
}

// GetBody returns the Body field value
func (o *RedditComment) GetBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *RedditComment) GetBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *RedditComment) SetBody(v string) {
	o.Body = v
}

// GetDate returns the Date field value
func (o *RedditComment) GetDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *RedditComment) GetDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *RedditComment) SetDate(v time.Time) {
	o.Date = v
}

// GetUpvotes returns the Upvotes field value
func (o *RedditComment) GetUpvotes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Upvotes
}

// GetUpvotesOk returns a tuple with the Upvotes field value
// and a boolean to check if the value has been set.
func (o *RedditComment) GetUpvotesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Upvotes, true
}

// SetUpvotes sets field value
func (o *RedditComment) SetUpvotes(v int32) {
	o.Upvotes = v
}

func (o RedditComment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RedditComment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["author"] = o.Author
	toSerialize["body"] = o.Body
	toSerialize["date"] = o.Date
	toSerialize["upvotes"] = o.Upvotes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RedditComment) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"author",
		"body",
		"date",
		"upvotes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRedditComment := _RedditComment{}

	err = json.Unmarshal(data, &varRedditComment)

	if err != nil {
		return err
	}

	*o = RedditComment(varRedditComment)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "author")
		delete(additionalProperties, "body")
		delete(additionalProperties, "date")
		delete(additionalProperties, "upvotes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRedditComment struct {
	value *RedditComment
	isSet bool
}

func (v NullableRedditComment) Get() *RedditComment {
	return v.value
}

func (v *NullableRedditComment) Set(val *RedditComment) {
	v.value = val
	v.isSet = true
}

func (v NullableRedditComment) IsSet() bool {
	return v.isSet
}

func (v *NullableRedditComment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRedditComment(val *RedditComment) *NullableRedditComment {
	return &NullableRedditComment{value: val, isSet: true}
}

func (v NullableRedditComment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRedditComment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


