/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.31.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the DomainMetricsTimeWindowResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainMetricsTimeWindowResponse{}

// DomainMetricsTimeWindowResponse struct for DomainMetricsTimeWindowResponse
type DomainMetricsTimeWindowResponse struct {
	Data []DomainMetricsDayItem `json:"data"`
	TotalSurfaces int32 `json:"total_surfaces"`
	TotalCitations int32 `json:"total_citations"`
	TotalFullText int32 `json:"total_full_text"`
	TotalGrounded *int32 `json:"total_grounded,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DomainMetricsTimeWindowResponse DomainMetricsTimeWindowResponse

// NewDomainMetricsTimeWindowResponse instantiates a new DomainMetricsTimeWindowResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainMetricsTimeWindowResponse(data []DomainMetricsDayItem, totalSurfaces int32, totalCitations int32, totalFullText int32) *DomainMetricsTimeWindowResponse {
	this := DomainMetricsTimeWindowResponse{}
	this.Data = data
	this.TotalSurfaces = totalSurfaces
	this.TotalCitations = totalCitations
	this.TotalFullText = totalFullText
	var totalGrounded int32 = 0
	this.TotalGrounded = &totalGrounded
	return &this
}

// NewDomainMetricsTimeWindowResponseWithDefaults instantiates a new DomainMetricsTimeWindowResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainMetricsTimeWindowResponseWithDefaults() *DomainMetricsTimeWindowResponse {
	this := DomainMetricsTimeWindowResponse{}
	var totalGrounded int32 = 0
	this.TotalGrounded = &totalGrounded
	return &this
}

// GetData returns the Data field value
func (o *DomainMetricsTimeWindowResponse) GetData() []DomainMetricsDayItem {
	if o == nil {
		var ret []DomainMetricsDayItem
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DomainMetricsTimeWindowResponse) GetDataOk() ([]DomainMetricsDayItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *DomainMetricsTimeWindowResponse) SetData(v []DomainMetricsDayItem) {
	o.Data = v
}

// GetTotalSurfaces returns the TotalSurfaces field value
func (o *DomainMetricsTimeWindowResponse) GetTotalSurfaces() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalSurfaces
}

// GetTotalSurfacesOk returns a tuple with the TotalSurfaces field value
// and a boolean to check if the value has been set.
func (o *DomainMetricsTimeWindowResponse) GetTotalSurfacesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalSurfaces, true
}

// SetTotalSurfaces sets field value
func (o *DomainMetricsTimeWindowResponse) SetTotalSurfaces(v int32) {
	o.TotalSurfaces = v
}

// GetTotalCitations returns the TotalCitations field value
func (o *DomainMetricsTimeWindowResponse) GetTotalCitations() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCitations
}

// GetTotalCitationsOk returns a tuple with the TotalCitations field value
// and a boolean to check if the value has been set.
func (o *DomainMetricsTimeWindowResponse) GetTotalCitationsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCitations, true
}

// SetTotalCitations sets field value
func (o *DomainMetricsTimeWindowResponse) SetTotalCitations(v int32) {
	o.TotalCitations = v
}

// GetTotalFullText returns the TotalFullText field value
func (o *DomainMetricsTimeWindowResponse) GetTotalFullText() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalFullText
}

// GetTotalFullTextOk returns a tuple with the TotalFullText field value
// and a boolean to check if the value has been set.
func (o *DomainMetricsTimeWindowResponse) GetTotalFullTextOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalFullText, true
}

// SetTotalFullText sets field value
func (o *DomainMetricsTimeWindowResponse) SetTotalFullText(v int32) {
	o.TotalFullText = v
}

// GetTotalGrounded returns the TotalGrounded field value if set, zero value otherwise.
func (o *DomainMetricsTimeWindowResponse) GetTotalGrounded() int32 {
	if o == nil || IsNil(o.TotalGrounded) {
		var ret int32
		return ret
	}
	return *o.TotalGrounded
}

// GetTotalGroundedOk returns a tuple with the TotalGrounded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainMetricsTimeWindowResponse) GetTotalGroundedOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalGrounded) {
		return nil, false
	}
	return o.TotalGrounded, true
}

// HasTotalGrounded returns a boolean if a field has been set.
func (o *DomainMetricsTimeWindowResponse) HasTotalGrounded() bool {
	if o != nil && !IsNil(o.TotalGrounded) {
		return true
	}

	return false
}

// SetTotalGrounded gets a reference to the given int32 and assigns it to the TotalGrounded field.
func (o *DomainMetricsTimeWindowResponse) SetTotalGrounded(v int32) {
	o.TotalGrounded = &v
}

func (o DomainMetricsTimeWindowResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainMetricsTimeWindowResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["total_surfaces"] = o.TotalSurfaces
	toSerialize["total_citations"] = o.TotalCitations
	toSerialize["total_full_text"] = o.TotalFullText
	if !IsNil(o.TotalGrounded) {
		toSerialize["total_grounded"] = o.TotalGrounded
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DomainMetricsTimeWindowResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"total_surfaces",
		"total_citations",
		"total_full_text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainMetricsTimeWindowResponse := _DomainMetricsTimeWindowResponse{}

	err = json.Unmarshal(data, &varDomainMetricsTimeWindowResponse)

	if err != nil {
		return err
	}

	*o = DomainMetricsTimeWindowResponse(varDomainMetricsTimeWindowResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "total_surfaces")
		delete(additionalProperties, "total_citations")
		delete(additionalProperties, "total_full_text")
		delete(additionalProperties, "total_grounded")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDomainMetricsTimeWindowResponse struct {
	value *DomainMetricsTimeWindowResponse
	isSet bool
}

func (v NullableDomainMetricsTimeWindowResponse) Get() *DomainMetricsTimeWindowResponse {
	return v.value
}

func (v *NullableDomainMetricsTimeWindowResponse) Set(val *DomainMetricsTimeWindowResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainMetricsTimeWindowResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainMetricsTimeWindowResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainMetricsTimeWindowResponse(val *DomainMetricsTimeWindowResponse) *NullableDomainMetricsTimeWindowResponse {
	return &NullableDomainMetricsTimeWindowResponse{value: val, isSet: true}
}

func (v NullableDomainMetricsTimeWindowResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainMetricsTimeWindowResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


