/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.27
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
)

// checks if the DeepNewsResponseSources1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeepNewsResponseSources1{}

// DeepNewsResponseSources1 struct for DeepNewsResponseSources1
type DeepNewsResponseSources1 struct {
	News []SearchResponseDictItem1 `json:"news,omitempty"`
	Web []WebSearchResult1 `json:"web,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DeepNewsResponseSources1 DeepNewsResponseSources1

// NewDeepNewsResponseSources1 instantiates a new DeepNewsResponseSources1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeepNewsResponseSources1() *DeepNewsResponseSources1 {
	this := DeepNewsResponseSources1{}
	return &this
}

// NewDeepNewsResponseSources1WithDefaults instantiates a new DeepNewsResponseSources1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeepNewsResponseSources1WithDefaults() *DeepNewsResponseSources1 {
	this := DeepNewsResponseSources1{}
	return &this
}

// GetNews returns the News field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeepNewsResponseSources1) GetNews() []SearchResponseDictItem1 {
	if o == nil {
		var ret []SearchResponseDictItem1
		return ret
	}
	return o.News
}

// GetNewsOk returns a tuple with the News field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeepNewsResponseSources1) GetNewsOk() ([]SearchResponseDictItem1, bool) {
	if o == nil || IsNil(o.News) {
		return nil, false
	}
	return o.News, true
}

// HasNews returns a boolean if a field has been set.
func (o *DeepNewsResponseSources1) HasNews() bool {
	if o != nil && !IsNil(o.News) {
		return true
	}

	return false
}

// SetNews gets a reference to the given []SearchResponseDictItem1 and assigns it to the News field.
func (o *DeepNewsResponseSources1) SetNews(v []SearchResponseDictItem1) {
	o.News = v
}

// GetWeb returns the Web field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeepNewsResponseSources1) GetWeb() []WebSearchResult1 {
	if o == nil {
		var ret []WebSearchResult1
		return ret
	}
	return o.Web
}

// GetWebOk returns a tuple with the Web field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeepNewsResponseSources1) GetWebOk() ([]WebSearchResult1, bool) {
	if o == nil || IsNil(o.Web) {
		return nil, false
	}
	return o.Web, true
}

// HasWeb returns a boolean if a field has been set.
func (o *DeepNewsResponseSources1) HasWeb() bool {
	if o != nil && !IsNil(o.Web) {
		return true
	}

	return false
}

// SetWeb gets a reference to the given []WebSearchResult1 and assigns it to the Web field.
func (o *DeepNewsResponseSources1) SetWeb(v []WebSearchResult1) {
	o.Web = v
}

func (o DeepNewsResponseSources1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeepNewsResponseSources1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.News != nil {
		toSerialize["news"] = o.News
	}
	if o.Web != nil {
		toSerialize["web"] = o.Web
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeepNewsResponseSources1) UnmarshalJSON(data []byte) (err error) {
	varDeepNewsResponseSources1 := _DeepNewsResponseSources1{}

	err = json.Unmarshal(data, &varDeepNewsResponseSources1)

	if err != nil {
		return err
	}

	*o = DeepNewsResponseSources1(varDeepNewsResponseSources1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "news")
		delete(additionalProperties, "web")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeepNewsResponseSources1 struct {
	value *DeepNewsResponseSources1
	isSet bool
}

func (v NullableDeepNewsResponseSources1) Get() *DeepNewsResponseSources1 {
	return v.value
}

func (v *NullableDeepNewsResponseSources1) Set(val *DeepNewsResponseSources1) {
	v.value = val
	v.isSet = true
}

func (v NullableDeepNewsResponseSources1) IsSet() bool {
	return v.isSet
}

func (v *NullableDeepNewsResponseSources1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeepNewsResponseSources1(val *DeepNewsResponseSources1) *NullableDeepNewsResponseSources1 {
	return &NullableDeepNewsResponseSources1{value: val, isSet: true}
}

func (v NullableDeepNewsResponseSources1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeepNewsResponseSources1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


