/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.27
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateChatCompletionRequestMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateChatCompletionRequestMessage{}

// CreateChatCompletionRequestMessage struct for CreateChatCompletionRequestMessage
type CreateChatCompletionRequestMessage struct {
	Role string `json:"role"`
	Content string `json:"content"`
	Name NullableString `json:"name,omitempty"`
	FunctionCall map[string]interface{} `json:"function_call,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateChatCompletionRequestMessage CreateChatCompletionRequestMessage

// NewCreateChatCompletionRequestMessage instantiates a new CreateChatCompletionRequestMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateChatCompletionRequestMessage(role string, content string) *CreateChatCompletionRequestMessage {
	this := CreateChatCompletionRequestMessage{}
	this.Role = role
	this.Content = content
	return &this
}

// NewCreateChatCompletionRequestMessageWithDefaults instantiates a new CreateChatCompletionRequestMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateChatCompletionRequestMessageWithDefaults() *CreateChatCompletionRequestMessage {
	this := CreateChatCompletionRequestMessage{}
	return &this
}

// GetRole returns the Role field value
func (o *CreateChatCompletionRequestMessage) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *CreateChatCompletionRequestMessage) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *CreateChatCompletionRequestMessage) SetRole(v string) {
	o.Role = v
}

// GetContent returns the Content field value
func (o *CreateChatCompletionRequestMessage) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *CreateChatCompletionRequestMessage) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *CreateChatCompletionRequestMessage) SetContent(v string) {
	o.Content = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateChatCompletionRequestMessage) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateChatCompletionRequestMessage) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *CreateChatCompletionRequestMessage) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *CreateChatCompletionRequestMessage) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *CreateChatCompletionRequestMessage) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *CreateChatCompletionRequestMessage) UnsetName() {
	o.Name.Unset()
}

// GetFunctionCall returns the FunctionCall field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateChatCompletionRequestMessage) GetFunctionCall() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.FunctionCall
}

// GetFunctionCallOk returns a tuple with the FunctionCall field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateChatCompletionRequestMessage) GetFunctionCallOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.FunctionCall) {
		return map[string]interface{}{}, false
	}
	return o.FunctionCall, true
}

// HasFunctionCall returns a boolean if a field has been set.
func (o *CreateChatCompletionRequestMessage) HasFunctionCall() bool {
	if o != nil && !IsNil(o.FunctionCall) {
		return true
	}

	return false
}

// SetFunctionCall gets a reference to the given map[string]interface{} and assigns it to the FunctionCall field.
func (o *CreateChatCompletionRequestMessage) SetFunctionCall(v map[string]interface{}) {
	o.FunctionCall = v
}

func (o CreateChatCompletionRequestMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateChatCompletionRequestMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	toSerialize["content"] = o.Content
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.FunctionCall != nil {
		toSerialize["function_call"] = o.FunctionCall
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateChatCompletionRequestMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateChatCompletionRequestMessage := _CreateChatCompletionRequestMessage{}

	err = json.Unmarshal(data, &varCreateChatCompletionRequestMessage)

	if err != nil {
		return err
	}

	*o = CreateChatCompletionRequestMessage(varCreateChatCompletionRequestMessage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "role")
		delete(additionalProperties, "content")
		delete(additionalProperties, "name")
		delete(additionalProperties, "function_call")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateChatCompletionRequestMessage struct {
	value *CreateChatCompletionRequestMessage
	isSet bool
}

func (v NullableCreateChatCompletionRequestMessage) Get() *CreateChatCompletionRequestMessage {
	return v.value
}

func (v *NullableCreateChatCompletionRequestMessage) Set(val *CreateChatCompletionRequestMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateChatCompletionRequestMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateChatCompletionRequestMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateChatCompletionRequestMessage(val *CreateChatCompletionRequestMessage) *NullableCreateChatCompletionRequestMessage {
	return &NullableCreateChatCompletionRequestMessage{value: val, isSet: true}
}

func (v NullableCreateChatCompletionRequestMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateChatCompletionRequestMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


