/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.66
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the ContentBlockDeltaEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentBlockDeltaEvent{}

// ContentBlockDeltaEvent struct for ContentBlockDeltaEvent
type ContentBlockDeltaEvent struct {
	Type *string `json:"type,omitempty"`
	Index int32 `json:"index"`
	Delta Delta1 `json:"delta"`
	AdditionalProperties map[string]interface{}
}

type _ContentBlockDeltaEvent ContentBlockDeltaEvent

// NewContentBlockDeltaEvent instantiates a new ContentBlockDeltaEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentBlockDeltaEvent(index int32, delta Delta1) *ContentBlockDeltaEvent {
	this := ContentBlockDeltaEvent{}
	var type_ string = "content_block_delta"
	this.Type = &type_
	this.Index = index
	this.Delta = delta
	return &this
}

// NewContentBlockDeltaEventWithDefaults instantiates a new ContentBlockDeltaEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentBlockDeltaEventWithDefaults() *ContentBlockDeltaEvent {
	this := ContentBlockDeltaEvent{}
	var type_ string = "content_block_delta"
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ContentBlockDeltaEvent) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentBlockDeltaEvent) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ContentBlockDeltaEvent) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ContentBlockDeltaEvent) SetType(v string) {
	o.Type = &v
}

// GetIndex returns the Index field value
func (o *ContentBlockDeltaEvent) GetIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *ContentBlockDeltaEvent) GetIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *ContentBlockDeltaEvent) SetIndex(v int32) {
	o.Index = v
}

// GetDelta returns the Delta field value
func (o *ContentBlockDeltaEvent) GetDelta() Delta1 {
	if o == nil {
		var ret Delta1
		return ret
	}

	return o.Delta
}

// GetDeltaOk returns a tuple with the Delta field value
// and a boolean to check if the value has been set.
func (o *ContentBlockDeltaEvent) GetDeltaOk() (*Delta1, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Delta, true
}

// SetDelta sets field value
func (o *ContentBlockDeltaEvent) SetDelta(v Delta1) {
	o.Delta = v
}

func (o ContentBlockDeltaEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentBlockDeltaEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	toSerialize["index"] = o.Index
	toSerialize["delta"] = o.Delta

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ContentBlockDeltaEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index",
		"delta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContentBlockDeltaEvent := _ContentBlockDeltaEvent{}

	err = json.Unmarshal(data, &varContentBlockDeltaEvent)

	if err != nil {
		return err
	}

	*o = ContentBlockDeltaEvent(varContentBlockDeltaEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "index")
		delete(additionalProperties, "delta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableContentBlockDeltaEvent struct {
	value *ContentBlockDeltaEvent
	isSet bool
}

func (v NullableContentBlockDeltaEvent) Get() *ContentBlockDeltaEvent {
	return v.value
}

func (v *NullableContentBlockDeltaEvent) Set(val *ContentBlockDeltaEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableContentBlockDeltaEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableContentBlockDeltaEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentBlockDeltaEvent(val *ContentBlockDeltaEvent) *NullableContentBlockDeltaEvent {
	return &NullableContentBlockDeltaEvent{value: val, isSet: true}
}

func (v NullableContentBlockDeltaEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentBlockDeltaEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


