/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.28
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the CirrusMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CirrusMetadata{}

// CirrusMetadata struct for CirrusMetadata
type CirrusMetadata struct {
	CreateTimestamp time.Time `json:"create_timestamp"`
	WikibaseItem string `json:"wikibase_item"`
	Version int32 `json:"version"`
	PopularityScore float32 `json:"popularity_score"`
	TextBytes int32 `json:"text_bytes"`
	AdditionalProperties map[string]interface{}
}

type _CirrusMetadata CirrusMetadata

// NewCirrusMetadata instantiates a new CirrusMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCirrusMetadata(createTimestamp time.Time, wikibaseItem string, version int32, popularityScore float32, textBytes int32) *CirrusMetadata {
	this := CirrusMetadata{}
	this.CreateTimestamp = createTimestamp
	this.WikibaseItem = wikibaseItem
	this.Version = version
	this.PopularityScore = popularityScore
	this.TextBytes = textBytes
	return &this
}

// NewCirrusMetadataWithDefaults instantiates a new CirrusMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCirrusMetadataWithDefaults() *CirrusMetadata {
	this := CirrusMetadata{}
	return &this
}

// GetCreateTimestamp returns the CreateTimestamp field value
func (o *CirrusMetadata) GetCreateTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreateTimestamp
}

// GetCreateTimestampOk returns a tuple with the CreateTimestamp field value
// and a boolean to check if the value has been set.
func (o *CirrusMetadata) GetCreateTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreateTimestamp, true
}

// SetCreateTimestamp sets field value
func (o *CirrusMetadata) SetCreateTimestamp(v time.Time) {
	o.CreateTimestamp = v
}

// GetWikibaseItem returns the WikibaseItem field value
func (o *CirrusMetadata) GetWikibaseItem() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WikibaseItem
}

// GetWikibaseItemOk returns a tuple with the WikibaseItem field value
// and a boolean to check if the value has been set.
func (o *CirrusMetadata) GetWikibaseItemOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WikibaseItem, true
}

// SetWikibaseItem sets field value
func (o *CirrusMetadata) SetWikibaseItem(v string) {
	o.WikibaseItem = v
}

// GetVersion returns the Version field value
func (o *CirrusMetadata) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *CirrusMetadata) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *CirrusMetadata) SetVersion(v int32) {
	o.Version = v
}

// GetPopularityScore returns the PopularityScore field value
func (o *CirrusMetadata) GetPopularityScore() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PopularityScore
}

// GetPopularityScoreOk returns a tuple with the PopularityScore field value
// and a boolean to check if the value has been set.
func (o *CirrusMetadata) GetPopularityScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PopularityScore, true
}

// SetPopularityScore sets field value
func (o *CirrusMetadata) SetPopularityScore(v float32) {
	o.PopularityScore = v
}

// GetTextBytes returns the TextBytes field value
func (o *CirrusMetadata) GetTextBytes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TextBytes
}

// GetTextBytesOk returns a tuple with the TextBytes field value
// and a boolean to check if the value has been set.
func (o *CirrusMetadata) GetTextBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TextBytes, true
}

// SetTextBytes sets field value
func (o *CirrusMetadata) SetTextBytes(v int32) {
	o.TextBytes = v
}

func (o CirrusMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CirrusMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["create_timestamp"] = o.CreateTimestamp
	toSerialize["wikibase_item"] = o.WikibaseItem
	toSerialize["version"] = o.Version
	toSerialize["popularity_score"] = o.PopularityScore
	toSerialize["text_bytes"] = o.TextBytes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CirrusMetadata) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"create_timestamp",
		"wikibase_item",
		"version",
		"popularity_score",
		"text_bytes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCirrusMetadata := _CirrusMetadata{}

	err = json.Unmarshal(data, &varCirrusMetadata)

	if err != nil {
		return err
	}

	*o = CirrusMetadata(varCirrusMetadata)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "create_timestamp")
		delete(additionalProperties, "wikibase_item")
		delete(additionalProperties, "version")
		delete(additionalProperties, "popularity_score")
		delete(additionalProperties, "text_bytes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCirrusMetadata struct {
	value *CirrusMetadata
	isSet bool
}

func (v NullableCirrusMetadata) Get() *CirrusMetadata {
	return v.value
}

func (v *NullableCirrusMetadata) Set(val *CirrusMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableCirrusMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableCirrusMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCirrusMetadata(val *CirrusMetadata) *NullableCirrusMetadata {
	return &NullableCirrusMetadata{value: val, isSet: true}
}

func (v NullableCirrusMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCirrusMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


