/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.50
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)


// CreateDeepNewsRequestModel The model to use for DeepNews research. Defaults to claude-sonnet-4-6.
type CreateDeepNewsRequestModel struct {
	DeepNewsModel *DeepNewsModel
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *CreateDeepNewsRequestModel) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into DeepNewsModel
	err = json.Unmarshal(data, &dst.DeepNewsModel);
	if err == nil {
		jsonDeepNewsModel, _ := json.Marshal(dst.DeepNewsModel)
		if string(jsonDeepNewsModel) == "{}" { // empty struct
			dst.DeepNewsModel = nil
		} else {
			return nil // data stored in dst.DeepNewsModel, return on the first match
		}
	} else {
		dst.DeepNewsModel = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(CreateDeepNewsRequestModel)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreateDeepNewsRequestModel) MarshalJSON() ([]byte, error) {
	if src.DeepNewsModel != nil {
		return json.Marshal(&src.DeepNewsModel)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableCreateDeepNewsRequestModel struct {
	value *CreateDeepNewsRequestModel
	isSet bool
}

func (v NullableCreateDeepNewsRequestModel) Get() *CreateDeepNewsRequestModel {
	return v.value
}

func (v *NullableCreateDeepNewsRequestModel) Set(val *CreateDeepNewsRequestModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDeepNewsRequestModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDeepNewsRequestModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDeepNewsRequestModel(val *CreateDeepNewsRequestModel) *NullableCreateDeepNewsRequestModel {
	return &NullableCreateDeepNewsRequestModel{value: val, isSet: true}
}

func (v NullableCreateDeepNewsRequestModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDeepNewsRequestModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


