/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.66
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"time"
	"fmt"
)


// CutoffDatetime The knowledge cutoff datetime for the agent prompt and all tool calls.
type CutoffDatetime struct {
	TimeTime *time.Time
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *CutoffDatetime) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into TimeTime
	err = json.Unmarshal(data, &dst.TimeTime);
	if err == nil {
		jsonTimeTime, _ := json.Marshal(dst.TimeTime)
		if string(jsonTimeTime) == "{}" { // empty struct
			dst.TimeTime = nil
		} else {
			return nil // data stored in dst.TimeTime, return on the first match
		}
	} else {
		dst.TimeTime = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(CutoffDatetime)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CutoffDatetime) MarshalJSON() ([]byte, error) {
	if src.TimeTime != nil {
		return json.Marshal(&src.TimeTime)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableCutoffDatetime struct {
	value *CutoffDatetime
	isSet bool
}

func (v NullableCutoffDatetime) Get() *CutoffDatetime {
	return v.value
}

func (v *NullableCutoffDatetime) Set(val *CutoffDatetime) {
	v.value = val
	v.isSet = true
}

func (v NullableCutoffDatetime) IsSet() bool {
	return v.isSet
}

func (v *NullableCutoffDatetime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCutoffDatetime(val *CutoffDatetime) *NullableCutoffDatetime {
	return &NullableCutoffDatetime{value: val, isSet: true}
}

func (v NullableCutoffDatetime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCutoffDatetime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


