/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.28
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)


// ReportingVoice1 struct for ReportingVoice1
type ReportingVoice1 struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ReportingVoice1) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ReportingVoice1)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ReportingVoice1) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableReportingVoice1 struct {
	value *ReportingVoice1
	isSet bool
}

func (v NullableReportingVoice1) Get() *ReportingVoice1 {
	return v.value
}

func (v *NullableReportingVoice1) Set(val *ReportingVoice1) {
	v.value = val
	v.isSet = true
}

func (v NullableReportingVoice1) IsSet() bool {
	return v.isSet
}

func (v *NullableReportingVoice1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportingVoice1(val *ReportingVoice1) *NullableReportingVoice1 {
	return &NullableReportingVoice1{value: val, isSet: true}
}

func (v NullableReportingVoice1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportingVoice1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


