/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.28
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the StoriesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoriesResponse{}

// StoriesResponse struct for StoriesResponse
type StoriesResponse struct {
	Stories []StoryResponse `json:"stories"`
	Offset Offset4 `json:"offset"`
	AdditionalProperties map[string]interface{}
}

type _StoriesResponse StoriesResponse

// NewStoriesResponse instantiates a new StoriesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoriesResponse(stories []StoryResponse, offset Offset4) *StoriesResponse {
	this := StoriesResponse{}
	this.Stories = stories
	this.Offset = offset
	return &this
}

// NewStoriesResponseWithDefaults instantiates a new StoriesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoriesResponseWithDefaults() *StoriesResponse {
	this := StoriesResponse{}
	return &this
}

// GetStories returns the Stories field value
func (o *StoriesResponse) GetStories() []StoryResponse {
	if o == nil {
		var ret []StoryResponse
		return ret
	}

	return o.Stories
}

// GetStoriesOk returns a tuple with the Stories field value
// and a boolean to check if the value has been set.
func (o *StoriesResponse) GetStoriesOk() ([]StoryResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Stories, true
}

// SetStories sets field value
func (o *StoriesResponse) SetStories(v []StoryResponse) {
	o.Stories = v
}

// GetOffset returns the Offset field value
func (o *StoriesResponse) GetOffset() Offset4 {
	if o == nil {
		var ret Offset4
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *StoriesResponse) GetOffsetOk() (*Offset4, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *StoriesResponse) SetOffset(v Offset4) {
	o.Offset = v
}

func (o StoriesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoriesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["stories"] = o.Stories
	toSerialize["offset"] = o.Offset

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StoriesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"stories",
		"offset",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStoriesResponse := _StoriesResponse{}

	err = json.Unmarshal(data, &varStoriesResponse)

	if err != nil {
		return err
	}

	*o = StoriesResponse(varStoriesResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "stories")
		delete(additionalProperties, "offset")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStoriesResponse struct {
	value *StoriesResponse
	isSet bool
}

func (v NullableStoriesResponse) Get() *StoriesResponse {
	return v.value
}

func (v *NullableStoriesResponse) Set(val *StoriesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStoriesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStoriesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoriesResponse(val *StoriesResponse) *NullableStoriesResponse {
	return &NullableStoriesResponse{value: val, isSet: true}
}

func (v NullableStoriesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoriesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


