/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.22
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateDeepNewsResponseUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDeepNewsResponseUsage{}

// CreateDeepNewsResponseUsage struct for CreateDeepNewsResponseUsage
type CreateDeepNewsResponseUsage struct {
	PromptTokens int32 `json:"prompt_tokens"`
	CompletionTokens int32 `json:"completion_tokens"`
	TotalTokens int32 `json:"total_tokens"`
	AdditionalProperties map[string]interface{}
}

type _CreateDeepNewsResponseUsage CreateDeepNewsResponseUsage

// NewCreateDeepNewsResponseUsage instantiates a new CreateDeepNewsResponseUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDeepNewsResponseUsage(promptTokens int32, completionTokens int32, totalTokens int32) *CreateDeepNewsResponseUsage {
	this := CreateDeepNewsResponseUsage{}
	this.PromptTokens = promptTokens
	this.CompletionTokens = completionTokens
	this.TotalTokens = totalTokens
	return &this
}

// NewCreateDeepNewsResponseUsageWithDefaults instantiates a new CreateDeepNewsResponseUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDeepNewsResponseUsageWithDefaults() *CreateDeepNewsResponseUsage {
	this := CreateDeepNewsResponseUsage{}
	return &this
}

// GetPromptTokens returns the PromptTokens field value
func (o *CreateDeepNewsResponseUsage) GetPromptTokens() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PromptTokens
}

// GetPromptTokensOk returns a tuple with the PromptTokens field value
// and a boolean to check if the value has been set.
func (o *CreateDeepNewsResponseUsage) GetPromptTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PromptTokens, true
}

// SetPromptTokens sets field value
func (o *CreateDeepNewsResponseUsage) SetPromptTokens(v int32) {
	o.PromptTokens = v
}

// GetCompletionTokens returns the CompletionTokens field value
func (o *CreateDeepNewsResponseUsage) GetCompletionTokens() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CompletionTokens
}

// GetCompletionTokensOk returns a tuple with the CompletionTokens field value
// and a boolean to check if the value has been set.
func (o *CreateDeepNewsResponseUsage) GetCompletionTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompletionTokens, true
}

// SetCompletionTokens sets field value
func (o *CreateDeepNewsResponseUsage) SetCompletionTokens(v int32) {
	o.CompletionTokens = v
}

// GetTotalTokens returns the TotalTokens field value
func (o *CreateDeepNewsResponseUsage) GetTotalTokens() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalTokens
}

// GetTotalTokensOk returns a tuple with the TotalTokens field value
// and a boolean to check if the value has been set.
func (o *CreateDeepNewsResponseUsage) GetTotalTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalTokens, true
}

// SetTotalTokens sets field value
func (o *CreateDeepNewsResponseUsage) SetTotalTokens(v int32) {
	o.TotalTokens = v
}

func (o CreateDeepNewsResponseUsage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDeepNewsResponseUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["prompt_tokens"] = o.PromptTokens
	toSerialize["completion_tokens"] = o.CompletionTokens
	toSerialize["total_tokens"] = o.TotalTokens

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateDeepNewsResponseUsage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"prompt_tokens",
		"completion_tokens",
		"total_tokens",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDeepNewsResponseUsage := _CreateDeepNewsResponseUsage{}

	err = json.Unmarshal(data, &varCreateDeepNewsResponseUsage)

	if err != nil {
		return err
	}

	*o = CreateDeepNewsResponseUsage(varCreateDeepNewsResponseUsage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "prompt_tokens")
		delete(additionalProperties, "completion_tokens")
		delete(additionalProperties, "total_tokens")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateDeepNewsResponseUsage struct {
	value *CreateDeepNewsResponseUsage
	isSet bool
}

func (v NullableCreateDeepNewsResponseUsage) Get() *CreateDeepNewsResponseUsage {
	return v.value
}

func (v *NullableCreateDeepNewsResponseUsage) Set(val *CreateDeepNewsResponseUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDeepNewsResponseUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDeepNewsResponseUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDeepNewsResponseUsage(val *CreateDeepNewsResponseUsage) *NullableCreateDeepNewsResponseUsage {
	return &NullableCreateDeepNewsResponseUsage{value: val, isSet: true}
}

func (v NullableCreateDeepNewsResponseUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDeepNewsResponseUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


