/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.28
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the OrganizationProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationProfile{}

// OrganizationProfile struct for OrganizationProfile
type OrganizationProfile struct {
	IdentityType *string `json:"identity_type,omitempty"`
	Id string `json:"id"`
	Subscription OrganizationProfileSubscription `json:"subscription"`
	AdditionalProperties map[string]interface{}
}

type _OrganizationProfile OrganizationProfile

// NewOrganizationProfile instantiates a new OrganizationProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationProfile(id string, subscription OrganizationProfileSubscription) *OrganizationProfile {
	this := OrganizationProfile{}
	var identityType string = "organization"
	this.IdentityType = &identityType
	this.Id = id
	this.Subscription = subscription
	return &this
}

// NewOrganizationProfileWithDefaults instantiates a new OrganizationProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationProfileWithDefaults() *OrganizationProfile {
	this := OrganizationProfile{}
	var identityType string = "organization"
	this.IdentityType = &identityType
	return &this
}

// GetIdentityType returns the IdentityType field value if set, zero value otherwise.
func (o *OrganizationProfile) GetIdentityType() string {
	if o == nil || IsNil(o.IdentityType) {
		var ret string
		return ret
	}
	return *o.IdentityType
}

// GetIdentityTypeOk returns a tuple with the IdentityType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationProfile) GetIdentityTypeOk() (*string, bool) {
	if o == nil || IsNil(o.IdentityType) {
		return nil, false
	}
	return o.IdentityType, true
}

// HasIdentityType returns a boolean if a field has been set.
func (o *OrganizationProfile) HasIdentityType() bool {
	if o != nil && !IsNil(o.IdentityType) {
		return true
	}

	return false
}

// SetIdentityType gets a reference to the given string and assigns it to the IdentityType field.
func (o *OrganizationProfile) SetIdentityType(v string) {
	o.IdentityType = &v
}

// GetId returns the Id field value
func (o *OrganizationProfile) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OrganizationProfile) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OrganizationProfile) SetId(v string) {
	o.Id = v
}

// GetSubscription returns the Subscription field value
func (o *OrganizationProfile) GetSubscription() OrganizationProfileSubscription {
	if o == nil {
		var ret OrganizationProfileSubscription
		return ret
	}

	return o.Subscription
}

// GetSubscriptionOk returns a tuple with the Subscription field value
// and a boolean to check if the value has been set.
func (o *OrganizationProfile) GetSubscriptionOk() (*OrganizationProfileSubscription, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subscription, true
}

// SetSubscription sets field value
func (o *OrganizationProfile) SetSubscription(v OrganizationProfileSubscription) {
	o.Subscription = v
}

func (o OrganizationProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IdentityType) {
		toSerialize["identity_type"] = o.IdentityType
	}
	toSerialize["id"] = o.Id
	toSerialize["subscription"] = o.Subscription

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrganizationProfile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"subscription",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationProfile := _OrganizationProfile{}

	err = json.Unmarshal(data, &varOrganizationProfile)

	if err != nil {
		return err
	}

	*o = OrganizationProfile(varOrganizationProfile)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "identity_type")
		delete(additionalProperties, "id")
		delete(additionalProperties, "subscription")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrganizationProfile struct {
	value *OrganizationProfile
	isSet bool
}

func (v NullableOrganizationProfile) Get() *OrganizationProfile {
	return v.value
}

func (v *NullableOrganizationProfile) Set(val *OrganizationProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationProfile(val *OrganizationProfile) *NullableOrganizationProfile {
	return &NullableOrganizationProfile{value: val, isSet: true}
}

func (v NullableOrganizationProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


