/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.27
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the TopNArticlesByHitsItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TopNArticlesByHitsItem{}

// TopNArticlesByHitsItem struct for TopNArticlesByHitsItem
type TopNArticlesByHitsItem struct {
	ArticleUrl string `json:"article_url"`
	HitCount int32 `json:"hit_count"`
	AdditionalProperties map[string]interface{}
}

type _TopNArticlesByHitsItem TopNArticlesByHitsItem

// NewTopNArticlesByHitsItem instantiates a new TopNArticlesByHitsItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTopNArticlesByHitsItem(articleUrl string, hitCount int32) *TopNArticlesByHitsItem {
	this := TopNArticlesByHitsItem{}
	this.ArticleUrl = articleUrl
	this.HitCount = hitCount
	return &this
}

// NewTopNArticlesByHitsItemWithDefaults instantiates a new TopNArticlesByHitsItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTopNArticlesByHitsItemWithDefaults() *TopNArticlesByHitsItem {
	this := TopNArticlesByHitsItem{}
	return &this
}

// GetArticleUrl returns the ArticleUrl field value
func (o *TopNArticlesByHitsItem) GetArticleUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ArticleUrl
}

// GetArticleUrlOk returns a tuple with the ArticleUrl field value
// and a boolean to check if the value has been set.
func (o *TopNArticlesByHitsItem) GetArticleUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArticleUrl, true
}

// SetArticleUrl sets field value
func (o *TopNArticlesByHitsItem) SetArticleUrl(v string) {
	o.ArticleUrl = v
}

// GetHitCount returns the HitCount field value
func (o *TopNArticlesByHitsItem) GetHitCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.HitCount
}

// GetHitCountOk returns a tuple with the HitCount field value
// and a boolean to check if the value has been set.
func (o *TopNArticlesByHitsItem) GetHitCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HitCount, true
}

// SetHitCount sets field value
func (o *TopNArticlesByHitsItem) SetHitCount(v int32) {
	o.HitCount = v
}

func (o TopNArticlesByHitsItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TopNArticlesByHitsItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["article_url"] = o.ArticleUrl
	toSerialize["hit_count"] = o.HitCount

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TopNArticlesByHitsItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"article_url",
		"hit_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTopNArticlesByHitsItem := _TopNArticlesByHitsItem{}

	err = json.Unmarshal(data, &varTopNArticlesByHitsItem)

	if err != nil {
		return err
	}

	*o = TopNArticlesByHitsItem(varTopNArticlesByHitsItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "article_url")
		delete(additionalProperties, "hit_count")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTopNArticlesByHitsItem struct {
	value *TopNArticlesByHitsItem
	isSet bool
}

func (v NullableTopNArticlesByHitsItem) Get() *TopNArticlesByHitsItem {
	return v.value
}

func (v *NullableTopNArticlesByHitsItem) Set(val *TopNArticlesByHitsItem) {
	v.value = val
	v.isSet = true
}

func (v NullableTopNArticlesByHitsItem) IsSet() bool {
	return v.isSet
}

func (v *NullableTopNArticlesByHitsItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTopNArticlesByHitsItem(val *TopNArticlesByHitsItem) *NullableTopNArticlesByHitsItem {
	return &NullableTopNArticlesByHitsItem{value: val, isSet: true}
}

func (v NullableTopNArticlesByHitsItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTopNArticlesByHitsItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


