/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.66
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateDeepNewsResponseStreamSourcesWebSource1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDeepNewsResponseStreamSourcesWebSource1{}

// CreateDeepNewsResponseStreamSourcesWebSource1 struct for CreateDeepNewsResponseStreamSourcesWebSource1
type CreateDeepNewsResponseStreamSourcesWebSource1 struct {
	Kind *string `json:"kind,omitempty"`
	Data WebSearchResult2 `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _CreateDeepNewsResponseStreamSourcesWebSource1 CreateDeepNewsResponseStreamSourcesWebSource1

// NewCreateDeepNewsResponseStreamSourcesWebSource1 instantiates a new CreateDeepNewsResponseStreamSourcesWebSource1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDeepNewsResponseStreamSourcesWebSource1(data WebSearchResult2) *CreateDeepNewsResponseStreamSourcesWebSource1 {
	this := CreateDeepNewsResponseStreamSourcesWebSource1{}
	var kind string = "web"
	this.Kind = &kind
	this.Data = data
	return &this
}

// NewCreateDeepNewsResponseStreamSourcesWebSource1WithDefaults instantiates a new CreateDeepNewsResponseStreamSourcesWebSource1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDeepNewsResponseStreamSourcesWebSource1WithDefaults() *CreateDeepNewsResponseStreamSourcesWebSource1 {
	this := CreateDeepNewsResponseStreamSourcesWebSource1{}
	var kind string = "web"
	this.Kind = &kind
	return &this
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *CreateDeepNewsResponseStreamSourcesWebSource1) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDeepNewsResponseStreamSourcesWebSource1) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *CreateDeepNewsResponseStreamSourcesWebSource1) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *CreateDeepNewsResponseStreamSourcesWebSource1) SetKind(v string) {
	o.Kind = &v
}

// GetData returns the Data field value
func (o *CreateDeepNewsResponseStreamSourcesWebSource1) GetData() WebSearchResult2 {
	if o == nil {
		var ret WebSearchResult2
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateDeepNewsResponseStreamSourcesWebSource1) GetDataOk() (*WebSearchResult2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateDeepNewsResponseStreamSourcesWebSource1) SetData(v WebSearchResult2) {
	o.Data = v
}

func (o CreateDeepNewsResponseStreamSourcesWebSource1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDeepNewsResponseStreamSourcesWebSource1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateDeepNewsResponseStreamSourcesWebSource1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDeepNewsResponseStreamSourcesWebSource1 := _CreateDeepNewsResponseStreamSourcesWebSource1{}

	err = json.Unmarshal(data, &varCreateDeepNewsResponseStreamSourcesWebSource1)

	if err != nil {
		return err
	}

	*o = CreateDeepNewsResponseStreamSourcesWebSource1(varCreateDeepNewsResponseStreamSourcesWebSource1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "kind")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateDeepNewsResponseStreamSourcesWebSource1 struct {
	value *CreateDeepNewsResponseStreamSourcesWebSource1
	isSet bool
}

func (v NullableCreateDeepNewsResponseStreamSourcesWebSource1) Get() *CreateDeepNewsResponseStreamSourcesWebSource1 {
	return v.value
}

func (v *NullableCreateDeepNewsResponseStreamSourcesWebSource1) Set(val *CreateDeepNewsResponseStreamSourcesWebSource1) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDeepNewsResponseStreamSourcesWebSource1) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDeepNewsResponseStreamSourcesWebSource1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDeepNewsResponseStreamSourcesWebSource1(val *CreateDeepNewsResponseStreamSourcesWebSource1) *NullableCreateDeepNewsResponseStreamSourcesWebSource1 {
	return &NullableCreateDeepNewsResponseStreamSourcesWebSource1{value: val, isSet: true}
}

func (v NullableCreateDeepNewsResponseStreamSourcesWebSource1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDeepNewsResponseStreamSourcesWebSource1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


