/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.22
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the WikiResponseDictItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WikiResponseDictItem{}

// WikiResponseDictItem struct for WikiResponseDictItem
type WikiResponseDictItem struct {
	Content string `json:"content"`
	Title string `json:"title"`
	Url string `json:"url"`
	Categories []string `json:"categories"`
	Timestamp time.Time `json:"timestamp"`
	CirrusMetadata NullableCirrusMetadata `json:"cirrus_metadata,omitempty"`
	PointId NullableString `json:"point_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WikiResponseDictItem WikiResponseDictItem

// NewWikiResponseDictItem instantiates a new WikiResponseDictItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWikiResponseDictItem(content string, title string, url string, categories []string, timestamp time.Time) *WikiResponseDictItem {
	this := WikiResponseDictItem{}
	this.Content = content
	this.Title = title
	this.Url = url
	this.Categories = categories
	this.Timestamp = timestamp
	return &this
}

// NewWikiResponseDictItemWithDefaults instantiates a new WikiResponseDictItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWikiResponseDictItemWithDefaults() *WikiResponseDictItem {
	this := WikiResponseDictItem{}
	return &this
}

// GetContent returns the Content field value
func (o *WikiResponseDictItem) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *WikiResponseDictItem) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *WikiResponseDictItem) SetContent(v string) {
	o.Content = v
}

// GetTitle returns the Title field value
func (o *WikiResponseDictItem) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *WikiResponseDictItem) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *WikiResponseDictItem) SetTitle(v string) {
	o.Title = v
}

// GetUrl returns the Url field value
func (o *WikiResponseDictItem) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WikiResponseDictItem) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WikiResponseDictItem) SetUrl(v string) {
	o.Url = v
}

// GetCategories returns the Categories field value
func (o *WikiResponseDictItem) GetCategories() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value
// and a boolean to check if the value has been set.
func (o *WikiResponseDictItem) GetCategoriesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Categories, true
}

// SetCategories sets field value
func (o *WikiResponseDictItem) SetCategories(v []string) {
	o.Categories = v
}

// GetTimestamp returns the Timestamp field value
func (o *WikiResponseDictItem) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *WikiResponseDictItem) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *WikiResponseDictItem) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetCirrusMetadata returns the CirrusMetadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WikiResponseDictItem) GetCirrusMetadata() CirrusMetadata {
	if o == nil || IsNil(o.CirrusMetadata.Get()) {
		var ret CirrusMetadata
		return ret
	}
	return *o.CirrusMetadata.Get()
}

// GetCirrusMetadataOk returns a tuple with the CirrusMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WikiResponseDictItem) GetCirrusMetadataOk() (*CirrusMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return o.CirrusMetadata.Get(), o.CirrusMetadata.IsSet()
}

// HasCirrusMetadata returns a boolean if a field has been set.
func (o *WikiResponseDictItem) HasCirrusMetadata() bool {
	if o != nil && o.CirrusMetadata.IsSet() {
		return true
	}

	return false
}

// SetCirrusMetadata gets a reference to the given NullableCirrusMetadata and assigns it to the CirrusMetadata field.
func (o *WikiResponseDictItem) SetCirrusMetadata(v CirrusMetadata) {
	o.CirrusMetadata.Set(&v)
}
// SetCirrusMetadataNil sets the value for CirrusMetadata to be an explicit nil
func (o *WikiResponseDictItem) SetCirrusMetadataNil() {
	o.CirrusMetadata.Set(nil)
}

// UnsetCirrusMetadata ensures that no value is present for CirrusMetadata, not even an explicit nil
func (o *WikiResponseDictItem) UnsetCirrusMetadata() {
	o.CirrusMetadata.Unset()
}

// GetPointId returns the PointId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WikiResponseDictItem) GetPointId() string {
	if o == nil || IsNil(o.PointId.Get()) {
		var ret string
		return ret
	}
	return *o.PointId.Get()
}

// GetPointIdOk returns a tuple with the PointId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WikiResponseDictItem) GetPointIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PointId.Get(), o.PointId.IsSet()
}

// HasPointId returns a boolean if a field has been set.
func (o *WikiResponseDictItem) HasPointId() bool {
	if o != nil && o.PointId.IsSet() {
		return true
	}

	return false
}

// SetPointId gets a reference to the given NullableString and assigns it to the PointId field.
func (o *WikiResponseDictItem) SetPointId(v string) {
	o.PointId.Set(&v)
}
// SetPointIdNil sets the value for PointId to be an explicit nil
func (o *WikiResponseDictItem) SetPointIdNil() {
	o.PointId.Set(nil)
}

// UnsetPointId ensures that no value is present for PointId, not even an explicit nil
func (o *WikiResponseDictItem) UnsetPointId() {
	o.PointId.Unset()
}

func (o WikiResponseDictItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WikiResponseDictItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["content"] = o.Content
	toSerialize["title"] = o.Title
	toSerialize["url"] = o.Url
	toSerialize["categories"] = o.Categories
	toSerialize["timestamp"] = o.Timestamp
	if o.CirrusMetadata.IsSet() {
		toSerialize["cirrus_metadata"] = o.CirrusMetadata.Get()
	}
	if o.PointId.IsSet() {
		toSerialize["point_id"] = o.PointId.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WikiResponseDictItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"content",
		"title",
		"url",
		"categories",
		"timestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWikiResponseDictItem := _WikiResponseDictItem{}

	err = json.Unmarshal(data, &varWikiResponseDictItem)

	if err != nil {
		return err
	}

	*o = WikiResponseDictItem(varWikiResponseDictItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "content")
		delete(additionalProperties, "title")
		delete(additionalProperties, "url")
		delete(additionalProperties, "categories")
		delete(additionalProperties, "timestamp")
		delete(additionalProperties, "cirrus_metadata")
		delete(additionalProperties, "point_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWikiResponseDictItem struct {
	value *WikiResponseDictItem
	isSet bool
}

func (v NullableWikiResponseDictItem) Get() *WikiResponseDictItem {
	return v.value
}

func (v *NullableWikiResponseDictItem) Set(val *WikiResponseDictItem) {
	v.value = val
	v.isSet = true
}

func (v NullableWikiResponseDictItem) IsSet() bool {
	return v.isSet
}

func (v *NullableWikiResponseDictItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWikiResponseDictItem(val *WikiResponseDictItem) *NullableWikiResponseDictItem {
	return &NullableWikiResponseDictItem{value: val, isSet: true}
}

func (v NullableWikiResponseDictItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWikiResponseDictItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


