/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.22
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the DomainHitsSurfaceTimeWindowResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainHitsSurfaceTimeWindowResponse{}

// DomainHitsSurfaceTimeWindowResponse struct for DomainHitsSurfaceTimeWindowResponse
type DomainHitsSurfaceTimeWindowResponse struct {
	Data []DomainHitsSurfaceDayItem `json:"data"`
	TotalHits int32 `json:"total_hits"`
	TotalSurfaced int32 `json:"total_surfaced"`
	AdditionalProperties map[string]interface{}
}

type _DomainHitsSurfaceTimeWindowResponse DomainHitsSurfaceTimeWindowResponse

// NewDomainHitsSurfaceTimeWindowResponse instantiates a new DomainHitsSurfaceTimeWindowResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainHitsSurfaceTimeWindowResponse(data []DomainHitsSurfaceDayItem, totalHits int32, totalSurfaced int32) *DomainHitsSurfaceTimeWindowResponse {
	this := DomainHitsSurfaceTimeWindowResponse{}
	this.Data = data
	this.TotalHits = totalHits
	this.TotalSurfaced = totalSurfaced
	return &this
}

// NewDomainHitsSurfaceTimeWindowResponseWithDefaults instantiates a new DomainHitsSurfaceTimeWindowResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainHitsSurfaceTimeWindowResponseWithDefaults() *DomainHitsSurfaceTimeWindowResponse {
	this := DomainHitsSurfaceTimeWindowResponse{}
	return &this
}

// GetData returns the Data field value
func (o *DomainHitsSurfaceTimeWindowResponse) GetData() []DomainHitsSurfaceDayItem {
	if o == nil {
		var ret []DomainHitsSurfaceDayItem
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DomainHitsSurfaceTimeWindowResponse) GetDataOk() ([]DomainHitsSurfaceDayItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *DomainHitsSurfaceTimeWindowResponse) SetData(v []DomainHitsSurfaceDayItem) {
	o.Data = v
}

// GetTotalHits returns the TotalHits field value
func (o *DomainHitsSurfaceTimeWindowResponse) GetTotalHits() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalHits
}

// GetTotalHitsOk returns a tuple with the TotalHits field value
// and a boolean to check if the value has been set.
func (o *DomainHitsSurfaceTimeWindowResponse) GetTotalHitsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalHits, true
}

// SetTotalHits sets field value
func (o *DomainHitsSurfaceTimeWindowResponse) SetTotalHits(v int32) {
	o.TotalHits = v
}

// GetTotalSurfaced returns the TotalSurfaced field value
func (o *DomainHitsSurfaceTimeWindowResponse) GetTotalSurfaced() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalSurfaced
}

// GetTotalSurfacedOk returns a tuple with the TotalSurfaced field value
// and a boolean to check if the value has been set.
func (o *DomainHitsSurfaceTimeWindowResponse) GetTotalSurfacedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalSurfaced, true
}

// SetTotalSurfaced sets field value
func (o *DomainHitsSurfaceTimeWindowResponse) SetTotalSurfaced(v int32) {
	o.TotalSurfaced = v
}

func (o DomainHitsSurfaceTimeWindowResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainHitsSurfaceTimeWindowResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["total_hits"] = o.TotalHits
	toSerialize["total_surfaced"] = o.TotalSurfaced

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DomainHitsSurfaceTimeWindowResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"total_hits",
		"total_surfaced",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainHitsSurfaceTimeWindowResponse := _DomainHitsSurfaceTimeWindowResponse{}

	err = json.Unmarshal(data, &varDomainHitsSurfaceTimeWindowResponse)

	if err != nil {
		return err
	}

	*o = DomainHitsSurfaceTimeWindowResponse(varDomainHitsSurfaceTimeWindowResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "total_hits")
		delete(additionalProperties, "total_surfaced")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDomainHitsSurfaceTimeWindowResponse struct {
	value *DomainHitsSurfaceTimeWindowResponse
	isSet bool
}

func (v NullableDomainHitsSurfaceTimeWindowResponse) Get() *DomainHitsSurfaceTimeWindowResponse {
	return v.value
}

func (v *NullableDomainHitsSurfaceTimeWindowResponse) Set(val *DomainHitsSurfaceTimeWindowResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainHitsSurfaceTimeWindowResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainHitsSurfaceTimeWindowResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainHitsSurfaceTimeWindowResponse(val *DomainHitsSurfaceTimeWindowResponse) *NullableDomainHitsSurfaceTimeWindowResponse {
	return &NullableDomainHitsSurfaceTimeWindowResponse{value: val, isSet: true}
}

func (v NullableDomainHitsSurfaceTimeWindowResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainHitsSurfaceTimeWindowResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


