/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.66
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the UpsertApiKeyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpsertApiKeyRequest{}

// UpsertApiKeyRequest struct for UpsertApiKeyRequest
type UpsertApiKeyRequest struct {
	ApiKey string `json:"api_key"`
	AdditionalProperties map[string]interface{}
}

type _UpsertApiKeyRequest UpsertApiKeyRequest

// NewUpsertApiKeyRequest instantiates a new UpsertApiKeyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpsertApiKeyRequest(apiKey string) *UpsertApiKeyRequest {
	this := UpsertApiKeyRequest{}
	this.ApiKey = apiKey
	return &this
}

// NewUpsertApiKeyRequestWithDefaults instantiates a new UpsertApiKeyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpsertApiKeyRequestWithDefaults() *UpsertApiKeyRequest {
	this := UpsertApiKeyRequest{}
	return &this
}

// GetApiKey returns the ApiKey field value
func (o *UpsertApiKeyRequest) GetApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *UpsertApiKeyRequest) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *UpsertApiKeyRequest) SetApiKey(v string) {
	o.ApiKey = v
}

func (o UpsertApiKeyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpsertApiKeyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["api_key"] = o.ApiKey

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpsertApiKeyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"api_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpsertApiKeyRequest := _UpsertApiKeyRequest{}

	err = json.Unmarshal(data, &varUpsertApiKeyRequest)

	if err != nil {
		return err
	}

	*o = UpsertApiKeyRequest(varUpsertApiKeyRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "api_key")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpsertApiKeyRequest struct {
	value *UpsertApiKeyRequest
	isSet bool
}

func (v NullableUpsertApiKeyRequest) Get() *UpsertApiKeyRequest {
	return v.value
}

func (v *NullableUpsertApiKeyRequest) Set(val *UpsertApiKeyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpsertApiKeyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpsertApiKeyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpsertApiKeyRequest(val *UpsertApiKeyRequest) *NullableUpsertApiKeyRequest {
	return &NullableUpsertApiKeyRequest{value: val, isSet: true}
}

func (v NullableUpsertApiKeyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpsertApiKeyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


