/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.66
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the AnthropicInputJsonDelta1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnthropicInputJsonDelta1{}

// AnthropicInputJsonDelta1 struct for AnthropicInputJsonDelta1
type AnthropicInputJsonDelta1 struct {
	Type *string `json:"type,omitempty"`
	PartialJson string `json:"partial_json"`
	AdditionalProperties map[string]interface{}
}

type _AnthropicInputJsonDelta1 AnthropicInputJsonDelta1

// NewAnthropicInputJsonDelta1 instantiates a new AnthropicInputJsonDelta1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnthropicInputJsonDelta1(partialJson string) *AnthropicInputJsonDelta1 {
	this := AnthropicInputJsonDelta1{}
	var type_ string = "input_json_delta"
	this.Type = &type_
	this.PartialJson = partialJson
	return &this
}

// NewAnthropicInputJsonDelta1WithDefaults instantiates a new AnthropicInputJsonDelta1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnthropicInputJsonDelta1WithDefaults() *AnthropicInputJsonDelta1 {
	this := AnthropicInputJsonDelta1{}
	var type_ string = "input_json_delta"
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *AnthropicInputJsonDelta1) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnthropicInputJsonDelta1) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *AnthropicInputJsonDelta1) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *AnthropicInputJsonDelta1) SetType(v string) {
	o.Type = &v
}

// GetPartialJson returns the PartialJson field value
func (o *AnthropicInputJsonDelta1) GetPartialJson() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PartialJson
}

// GetPartialJsonOk returns a tuple with the PartialJson field value
// and a boolean to check if the value has been set.
func (o *AnthropicInputJsonDelta1) GetPartialJsonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartialJson, true
}

// SetPartialJson sets field value
func (o *AnthropicInputJsonDelta1) SetPartialJson(v string) {
	o.PartialJson = v
}

func (o AnthropicInputJsonDelta1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnthropicInputJsonDelta1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	toSerialize["partial_json"] = o.PartialJson

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AnthropicInputJsonDelta1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"partial_json",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAnthropicInputJsonDelta1 := _AnthropicInputJsonDelta1{}

	err = json.Unmarshal(data, &varAnthropicInputJsonDelta1)

	if err != nil {
		return err
	}

	*o = AnthropicInputJsonDelta1(varAnthropicInputJsonDelta1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "partial_json")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAnthropicInputJsonDelta1 struct {
	value *AnthropicInputJsonDelta1
	isSet bool
}

func (v NullableAnthropicInputJsonDelta1) Get() *AnthropicInputJsonDelta1 {
	return v.value
}

func (v *NullableAnthropicInputJsonDelta1) Set(val *AnthropicInputJsonDelta1) {
	v.value = val
	v.isSet = true
}

func (v NullableAnthropicInputJsonDelta1) IsSet() bool {
	return v.isSet
}

func (v *NullableAnthropicInputJsonDelta1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnthropicInputJsonDelta1(val *AnthropicInputJsonDelta1) *NullableAnthropicInputJsonDelta1 {
	return &NullableAnthropicInputJsonDelta1{value: val, isSet: true}
}

func (v NullableAnthropicInputJsonDelta1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnthropicInputJsonDelta1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


