/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.66
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the ContentBlockStopEvent1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentBlockStopEvent1{}

// ContentBlockStopEvent1 struct for ContentBlockStopEvent1
type ContentBlockStopEvent1 struct {
	Type *string `json:"type,omitempty"`
	Index int32 `json:"index"`
	AdditionalProperties map[string]interface{}
}

type _ContentBlockStopEvent1 ContentBlockStopEvent1

// NewContentBlockStopEvent1 instantiates a new ContentBlockStopEvent1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentBlockStopEvent1(index int32) *ContentBlockStopEvent1 {
	this := ContentBlockStopEvent1{}
	var type_ string = "content_block_stop"
	this.Type = &type_
	this.Index = index
	return &this
}

// NewContentBlockStopEvent1WithDefaults instantiates a new ContentBlockStopEvent1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentBlockStopEvent1WithDefaults() *ContentBlockStopEvent1 {
	this := ContentBlockStopEvent1{}
	var type_ string = "content_block_stop"
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ContentBlockStopEvent1) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentBlockStopEvent1) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ContentBlockStopEvent1) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ContentBlockStopEvent1) SetType(v string) {
	o.Type = &v
}

// GetIndex returns the Index field value
func (o *ContentBlockStopEvent1) GetIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *ContentBlockStopEvent1) GetIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *ContentBlockStopEvent1) SetIndex(v int32) {
	o.Index = v
}

func (o ContentBlockStopEvent1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentBlockStopEvent1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	toSerialize["index"] = o.Index

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ContentBlockStopEvent1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContentBlockStopEvent1 := _ContentBlockStopEvent1{}

	err = json.Unmarshal(data, &varContentBlockStopEvent1)

	if err != nil {
		return err
	}

	*o = ContentBlockStopEvent1(varContentBlockStopEvent1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "index")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableContentBlockStopEvent1 struct {
	value *ContentBlockStopEvent1
	isSet bool
}

func (v NullableContentBlockStopEvent1) Get() *ContentBlockStopEvent1 {
	return v.value
}

func (v *NullableContentBlockStopEvent1) Set(val *ContentBlockStopEvent1) {
	v.value = val
	v.isSet = true
}

func (v NullableContentBlockStopEvent1) IsSet() bool {
	return v.isSet
}

func (v *NullableContentBlockStopEvent1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentBlockStopEvent1(val *ContentBlockStopEvent1) *NullableContentBlockStopEvent1 {
	return &NullableContentBlockStopEvent1{value: val, isSet: true}
}

func (v NullableContentBlockStopEvent1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentBlockStopEvent1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


