/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.50
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// CreateAlertRequestReport - struct for CreateAlertRequestReport
type CreateAlertRequestReport struct {
	DeepNewsReportRequest *DeepNewsReportRequest
	LegacyReportRequest *LegacyReportRequest
}

// DeepNewsReportRequestAsCreateAlertRequestReport is a convenience function that returns DeepNewsReportRequest wrapped in CreateAlertRequestReport
func DeepNewsReportRequestAsCreateAlertRequestReport(v *DeepNewsReportRequest) CreateAlertRequestReport {
	return CreateAlertRequestReport{
		DeepNewsReportRequest: v,
	}
}

// LegacyReportRequestAsCreateAlertRequestReport is a convenience function that returns LegacyReportRequest wrapped in CreateAlertRequestReport
func LegacyReportRequestAsCreateAlertRequestReport(v *LegacyReportRequest) CreateAlertRequestReport {
	return CreateAlertRequestReport{
		LegacyReportRequest: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CreateAlertRequestReport) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into DeepNewsReportRequest
	err = newStrictDecoder(data).Decode(&dst.DeepNewsReportRequest)
	if err == nil {
		jsonDeepNewsReportRequest, _ := json.Marshal(dst.DeepNewsReportRequest)
		if string(jsonDeepNewsReportRequest) == "{}" { // empty struct
			dst.DeepNewsReportRequest = nil
		} else {
			if err = validator.Validate(dst.DeepNewsReportRequest); err != nil {
				dst.DeepNewsReportRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.DeepNewsReportRequest = nil
	}

	// try to unmarshal data into LegacyReportRequest
	err = newStrictDecoder(data).Decode(&dst.LegacyReportRequest)
	if err == nil {
		jsonLegacyReportRequest, _ := json.Marshal(dst.LegacyReportRequest)
		if string(jsonLegacyReportRequest) == "{}" { // empty struct
			dst.LegacyReportRequest = nil
		} else {
			if err = validator.Validate(dst.LegacyReportRequest); err != nil {
				dst.LegacyReportRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.LegacyReportRequest = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.DeepNewsReportRequest = nil
		dst.LegacyReportRequest = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CreateAlertRequestReport)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CreateAlertRequestReport)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreateAlertRequestReport) MarshalJSON() ([]byte, error) {
	if src.DeepNewsReportRequest != nil {
		return json.Marshal(&src.DeepNewsReportRequest)
	}

	if src.LegacyReportRequest != nil {
		return json.Marshal(&src.LegacyReportRequest)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CreateAlertRequestReport) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.DeepNewsReportRequest != nil {
		return obj.DeepNewsReportRequest
	}

	if obj.LegacyReportRequest != nil {
		return obj.LegacyReportRequest
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CreateAlertRequestReport) GetActualInstanceValue() (interface{}) {
	if obj.DeepNewsReportRequest != nil {
		return *obj.DeepNewsReportRequest
	}

	if obj.LegacyReportRequest != nil {
		return *obj.LegacyReportRequest
	}

	// all schemas are nil
	return nil
}

type NullableCreateAlertRequestReport struct {
	value *CreateAlertRequestReport
	isSet bool
}

func (v NullableCreateAlertRequestReport) Get() *CreateAlertRequestReport {
	return v.value
}

func (v *NullableCreateAlertRequestReport) Set(val *CreateAlertRequestReport) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAlertRequestReport) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAlertRequestReport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAlertRequestReport(val *CreateAlertRequestReport) *NullableCreateAlertRequestReport {
	return &NullableCreateAlertRequestReport{value: val, isSet: true}
}

func (v NullableCreateAlertRequestReport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAlertRequestReport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


