/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.22
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the AbcAPIErrorModel52 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AbcAPIErrorModel52{}

// AbcAPIErrorModel52 struct for AbcAPIErrorModel52
type AbcAPIErrorModel52 struct {
	Code int32 `json:"code"`
	Detail string `json:"detail"`
	AdditionalProperties map[string]interface{}
}

type _AbcAPIErrorModel52 AbcAPIErrorModel52

// NewAbcAPIErrorModel52 instantiates a new AbcAPIErrorModel52 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAbcAPIErrorModel52(code int32, detail string) *AbcAPIErrorModel52 {
	this := AbcAPIErrorModel52{}
	this.Code = code
	this.Detail = detail
	return &this
}

// NewAbcAPIErrorModel52WithDefaults instantiates a new AbcAPIErrorModel52 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAbcAPIErrorModel52WithDefaults() *AbcAPIErrorModel52 {
	this := AbcAPIErrorModel52{}
	return &this
}

// GetCode returns the Code field value
func (o *AbcAPIErrorModel52) GetCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *AbcAPIErrorModel52) GetCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *AbcAPIErrorModel52) SetCode(v int32) {
	o.Code = v
}

// GetDetail returns the Detail field value
func (o *AbcAPIErrorModel52) GetDetail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Detail
}

// GetDetailOk returns a tuple with the Detail field value
// and a boolean to check if the value has been set.
func (o *AbcAPIErrorModel52) GetDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Detail, true
}

// SetDetail sets field value
func (o *AbcAPIErrorModel52) SetDetail(v string) {
	o.Detail = v
}

func (o AbcAPIErrorModel52) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AbcAPIErrorModel52) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["detail"] = o.Detail

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AbcAPIErrorModel52) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"detail",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAbcAPIErrorModel52 := _AbcAPIErrorModel52{}

	err = json.Unmarshal(data, &varAbcAPIErrorModel52)

	if err != nil {
		return err
	}

	*o = AbcAPIErrorModel52(varAbcAPIErrorModel52)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "detail")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAbcAPIErrorModel52 struct {
	value *AbcAPIErrorModel52
	isSet bool
}

func (v NullableAbcAPIErrorModel52) Get() *AbcAPIErrorModel52 {
	return v.value
}

func (v *NullableAbcAPIErrorModel52) Set(val *AbcAPIErrorModel52) {
	v.value = val
	v.isSet = true
}

func (v NullableAbcAPIErrorModel52) IsSet() bool {
	return v.isSet
}

func (v *NullableAbcAPIErrorModel52) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAbcAPIErrorModel52(val *AbcAPIErrorModel52) *NullableAbcAPIErrorModel52 {
	return &NullableAbcAPIErrorModel52{value: val, isSet: true}
}

func (v NullableAbcAPIErrorModel52) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAbcAPIErrorModel52) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


