/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.27
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the DomainQueryArticleItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainQueryArticleItem{}

// DomainQueryArticleItem struct for DomainQueryArticleItem
type DomainQueryArticleItem struct {
	ArticleId string `json:"article_id"`
	HitDate string `json:"hit_date"`
	AdditionalProperties map[string]interface{}
}

type _DomainQueryArticleItem DomainQueryArticleItem

// NewDomainQueryArticleItem instantiates a new DomainQueryArticleItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainQueryArticleItem(articleId string, hitDate string) *DomainQueryArticleItem {
	this := DomainQueryArticleItem{}
	this.ArticleId = articleId
	this.HitDate = hitDate
	return &this
}

// NewDomainQueryArticleItemWithDefaults instantiates a new DomainQueryArticleItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainQueryArticleItemWithDefaults() *DomainQueryArticleItem {
	this := DomainQueryArticleItem{}
	return &this
}

// GetArticleId returns the ArticleId field value
func (o *DomainQueryArticleItem) GetArticleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ArticleId
}

// GetArticleIdOk returns a tuple with the ArticleId field value
// and a boolean to check if the value has been set.
func (o *DomainQueryArticleItem) GetArticleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArticleId, true
}

// SetArticleId sets field value
func (o *DomainQueryArticleItem) SetArticleId(v string) {
	o.ArticleId = v
}

// GetHitDate returns the HitDate field value
func (o *DomainQueryArticleItem) GetHitDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HitDate
}

// GetHitDateOk returns a tuple with the HitDate field value
// and a boolean to check if the value has been set.
func (o *DomainQueryArticleItem) GetHitDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HitDate, true
}

// SetHitDate sets field value
func (o *DomainQueryArticleItem) SetHitDate(v string) {
	o.HitDate = v
}

func (o DomainQueryArticleItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainQueryArticleItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["article_id"] = o.ArticleId
	toSerialize["hit_date"] = o.HitDate

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DomainQueryArticleItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"article_id",
		"hit_date",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainQueryArticleItem := _DomainQueryArticleItem{}

	err = json.Unmarshal(data, &varDomainQueryArticleItem)

	if err != nil {
		return err
	}

	*o = DomainQueryArticleItem(varDomainQueryArticleItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "article_id")
		delete(additionalProperties, "hit_date")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDomainQueryArticleItem struct {
	value *DomainQueryArticleItem
	isSet bool
}

func (v NullableDomainQueryArticleItem) Get() *DomainQueryArticleItem {
	return v.value
}

func (v *NullableDomainQueryArticleItem) Set(val *DomainQueryArticleItem) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainQueryArticleItem) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainQueryArticleItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainQueryArticleItem(val *DomainQueryArticleItem) *NullableDomainQueryArticleItem {
	return &NullableDomainQueryArticleItem{value: val, isSet: true}
}

func (v NullableDomainQueryArticleItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainQueryArticleItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


