/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.27
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateDeepNewsResponseStreamSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDeepNewsResponseStreamSource{}

// CreateDeepNewsResponseStreamSource struct for CreateDeepNewsResponseStreamSource
type CreateDeepNewsResponseStreamSource struct {
	Id string `json:"id"`
	Created int32 `json:"created"`
	Object *string `json:"object,omitempty"`
	Source Source `json:"source"`
	AdditionalProperties map[string]interface{}
}

type _CreateDeepNewsResponseStreamSource CreateDeepNewsResponseStreamSource

// NewCreateDeepNewsResponseStreamSource instantiates a new CreateDeepNewsResponseStreamSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDeepNewsResponseStreamSource(id string, created int32, source Source) *CreateDeepNewsResponseStreamSource {
	this := CreateDeepNewsResponseStreamSource{}
	this.Id = id
	this.Created = created
	var object string = "chat.completion.source"
	this.Object = &object
	this.Source = source
	return &this
}

// NewCreateDeepNewsResponseStreamSourceWithDefaults instantiates a new CreateDeepNewsResponseStreamSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDeepNewsResponseStreamSourceWithDefaults() *CreateDeepNewsResponseStreamSource {
	this := CreateDeepNewsResponseStreamSource{}
	var object string = "chat.completion.source"
	this.Object = &object
	return &this
}

// GetId returns the Id field value
func (o *CreateDeepNewsResponseStreamSource) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateDeepNewsResponseStreamSource) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateDeepNewsResponseStreamSource) SetId(v string) {
	o.Id = v
}

// GetCreated returns the Created field value
func (o *CreateDeepNewsResponseStreamSource) GetCreated() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *CreateDeepNewsResponseStreamSource) GetCreatedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *CreateDeepNewsResponseStreamSource) SetCreated(v int32) {
	o.Created = v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *CreateDeepNewsResponseStreamSource) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDeepNewsResponseStreamSource) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *CreateDeepNewsResponseStreamSource) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *CreateDeepNewsResponseStreamSource) SetObject(v string) {
	o.Object = &v
}

// GetSource returns the Source field value
func (o *CreateDeepNewsResponseStreamSource) GetSource() Source {
	if o == nil {
		var ret Source
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *CreateDeepNewsResponseStreamSource) GetSourceOk() (*Source, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *CreateDeepNewsResponseStreamSource) SetSource(v Source) {
	o.Source = v
}

func (o CreateDeepNewsResponseStreamSource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDeepNewsResponseStreamSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["created"] = o.Created
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	toSerialize["source"] = o.Source

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateDeepNewsResponseStreamSource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"created",
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDeepNewsResponseStreamSource := _CreateDeepNewsResponseStreamSource{}

	err = json.Unmarshal(data, &varCreateDeepNewsResponseStreamSource)

	if err != nil {
		return err
	}

	*o = CreateDeepNewsResponseStreamSource(varCreateDeepNewsResponseStreamSource)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "created")
		delete(additionalProperties, "object")
		delete(additionalProperties, "source")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateDeepNewsResponseStreamSource struct {
	value *CreateDeepNewsResponseStreamSource
	isSet bool
}

func (v NullableCreateDeepNewsResponseStreamSource) Get() *CreateDeepNewsResponseStreamSource {
	return v.value
}

func (v *NullableCreateDeepNewsResponseStreamSource) Set(val *CreateDeepNewsResponseStreamSource) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDeepNewsResponseStreamSource) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDeepNewsResponseStreamSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDeepNewsResponseStreamSource(val *CreateDeepNewsResponseStreamSource) *NullableCreateDeepNewsResponseStreamSource {
	return &NullableCreateDeepNewsResponseStreamSource{value: val, isSet: true}
}

func (v NullableCreateDeepNewsResponseStreamSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDeepNewsResponseStreamSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


