/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.66
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// Delta1 - struct for Delta1
type Delta1 struct {
	AnthropicInputJsonDelta *AnthropicInputJsonDelta
	AnthropicTextDelta *AnthropicTextDelta
	AnthropicThinkingDelta *AnthropicThinkingDelta
}

// AnthropicInputJsonDeltaAsDelta1 is a convenience function that returns AnthropicInputJsonDelta wrapped in Delta1
func AnthropicInputJsonDeltaAsDelta1(v *AnthropicInputJsonDelta) Delta1 {
	return Delta1{
		AnthropicInputJsonDelta: v,
	}
}

// AnthropicTextDeltaAsDelta1 is a convenience function that returns AnthropicTextDelta wrapped in Delta1
func AnthropicTextDeltaAsDelta1(v *AnthropicTextDelta) Delta1 {
	return Delta1{
		AnthropicTextDelta: v,
	}
}

// AnthropicThinkingDeltaAsDelta1 is a convenience function that returns AnthropicThinkingDelta wrapped in Delta1
func AnthropicThinkingDeltaAsDelta1(v *AnthropicThinkingDelta) Delta1 {
	return Delta1{
		AnthropicThinkingDelta: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *Delta1) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AnthropicInputJsonDelta
	err = newStrictDecoder(data).Decode(&dst.AnthropicInputJsonDelta)
	if err == nil {
		jsonAnthropicInputJsonDelta, _ := json.Marshal(dst.AnthropicInputJsonDelta)
		if string(jsonAnthropicInputJsonDelta) == "{}" { // empty struct
			dst.AnthropicInputJsonDelta = nil
		} else {
			if err = validator.Validate(dst.AnthropicInputJsonDelta); err != nil {
				dst.AnthropicInputJsonDelta = nil
			} else {
				match++
			}
		}
	} else {
		dst.AnthropicInputJsonDelta = nil
	}

	// try to unmarshal data into AnthropicTextDelta
	err = newStrictDecoder(data).Decode(&dst.AnthropicTextDelta)
	if err == nil {
		jsonAnthropicTextDelta, _ := json.Marshal(dst.AnthropicTextDelta)
		if string(jsonAnthropicTextDelta) == "{}" { // empty struct
			dst.AnthropicTextDelta = nil
		} else {
			if err = validator.Validate(dst.AnthropicTextDelta); err != nil {
				dst.AnthropicTextDelta = nil
			} else {
				match++
			}
		}
	} else {
		dst.AnthropicTextDelta = nil
	}

	// try to unmarshal data into AnthropicThinkingDelta
	err = newStrictDecoder(data).Decode(&dst.AnthropicThinkingDelta)
	if err == nil {
		jsonAnthropicThinkingDelta, _ := json.Marshal(dst.AnthropicThinkingDelta)
		if string(jsonAnthropicThinkingDelta) == "{}" { // empty struct
			dst.AnthropicThinkingDelta = nil
		} else {
			if err = validator.Validate(dst.AnthropicThinkingDelta); err != nil {
				dst.AnthropicThinkingDelta = nil
			} else {
				match++
			}
		}
	} else {
		dst.AnthropicThinkingDelta = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AnthropicInputJsonDelta = nil
		dst.AnthropicTextDelta = nil
		dst.AnthropicThinkingDelta = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Delta1)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(Delta1)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Delta1) MarshalJSON() ([]byte, error) {
	if src.AnthropicInputJsonDelta != nil {
		return json.Marshal(&src.AnthropicInputJsonDelta)
	}

	if src.AnthropicTextDelta != nil {
		return json.Marshal(&src.AnthropicTextDelta)
	}

	if src.AnthropicThinkingDelta != nil {
		return json.Marshal(&src.AnthropicThinkingDelta)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Delta1) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.AnthropicInputJsonDelta != nil {
		return obj.AnthropicInputJsonDelta
	}

	if obj.AnthropicTextDelta != nil {
		return obj.AnthropicTextDelta
	}

	if obj.AnthropicThinkingDelta != nil {
		return obj.AnthropicThinkingDelta
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj Delta1) GetActualInstanceValue() (interface{}) {
	if obj.AnthropicInputJsonDelta != nil {
		return *obj.AnthropicInputJsonDelta
	}

	if obj.AnthropicTextDelta != nil {
		return *obj.AnthropicTextDelta
	}

	if obj.AnthropicThinkingDelta != nil {
		return *obj.AnthropicThinkingDelta
	}

	// all schemas are nil
	return nil
}

type NullableDelta1 struct {
	value *Delta1
	isSet bool
}

func (v NullableDelta1) Get() *Delta1 {
	return v.value
}

func (v *NullableDelta1) Set(val *Delta1) {
	v.value = val
	v.isSet = true
}

func (v NullableDelta1) IsSet() bool {
	return v.isSet
}

func (v *NullableDelta1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDelta1(val *Delta1) *NullableDelta1 {
	return &NullableDelta1{value: val, isSet: true}
}

func (v NullableDelta1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDelta1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


