/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.27
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the GoogleDocsParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GoogleDocsParams{}

// GoogleDocsParams struct for GoogleDocsParams
type GoogleDocsParams struct {
	// The google service account json. This should be a dict. You can get this from the google cloud console. The document will be created in the service account's google drive and shared with the user.
	ClientJson map[string]interface{} `json:"client_json"`
	Emails []string `json:"emails,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GoogleDocsParams GoogleDocsParams

// NewGoogleDocsParams instantiates a new GoogleDocsParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoogleDocsParams(clientJson map[string]interface{}) *GoogleDocsParams {
	this := GoogleDocsParams{}
	this.ClientJson = clientJson
	return &this
}

// NewGoogleDocsParamsWithDefaults instantiates a new GoogleDocsParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoogleDocsParamsWithDefaults() *GoogleDocsParams {
	this := GoogleDocsParams{}
	return &this
}

// GetClientJson returns the ClientJson field value
func (o *GoogleDocsParams) GetClientJson() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.ClientJson
}

// GetClientJsonOk returns a tuple with the ClientJson field value
// and a boolean to check if the value has been set.
func (o *GoogleDocsParams) GetClientJsonOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.ClientJson, true
}

// SetClientJson sets field value
func (o *GoogleDocsParams) SetClientJson(v map[string]interface{}) {
	o.ClientJson = v
}

// GetEmails returns the Emails field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GoogleDocsParams) GetEmails() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Emails
}

// GetEmailsOk returns a tuple with the Emails field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GoogleDocsParams) GetEmailsOk() ([]string, bool) {
	if o == nil || IsNil(o.Emails) {
		return nil, false
	}
	return o.Emails, true
}

// HasEmails returns a boolean if a field has been set.
func (o *GoogleDocsParams) HasEmails() bool {
	if o != nil && !IsNil(o.Emails) {
		return true
	}

	return false
}

// SetEmails gets a reference to the given []string and assigns it to the Emails field.
func (o *GoogleDocsParams) SetEmails(v []string) {
	o.Emails = v
}

func (o GoogleDocsParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GoogleDocsParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["client_json"] = o.ClientJson
	if o.Emails != nil {
		toSerialize["emails"] = o.Emails
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GoogleDocsParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"client_json",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGoogleDocsParams := _GoogleDocsParams{}

	err = json.Unmarshal(data, &varGoogleDocsParams)

	if err != nil {
		return err
	}

	*o = GoogleDocsParams(varGoogleDocsParams)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "client_json")
		delete(additionalProperties, "emails")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGoogleDocsParams struct {
	value *GoogleDocsParams
	isSet bool
}

func (v NullableGoogleDocsParams) Get() *GoogleDocsParams {
	return v.value
}

func (v *NullableGoogleDocsParams) Set(val *GoogleDocsParams) {
	v.value = val
	v.isSet = true
}

func (v NullableGoogleDocsParams) IsSet() bool {
	return v.isSet
}

func (v *NullableGoogleDocsParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoogleDocsParams(val *GoogleDocsParams) *NullableGoogleDocsParams {
	return &NullableGoogleDocsParams{value: val, isSet: true}
}

func (v NullableGoogleDocsParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoogleDocsParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


