/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.50
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the ListDeepNewsModelResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDeepNewsModelResponse{}

// ListDeepNewsModelResponse struct for ListDeepNewsModelResponse
type ListDeepNewsModelResponse struct {
	Models []DeepNewsModelItem `json:"models"`
	AdditionalProperties map[string]interface{}
}

type _ListDeepNewsModelResponse ListDeepNewsModelResponse

// NewListDeepNewsModelResponse instantiates a new ListDeepNewsModelResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDeepNewsModelResponse(models []DeepNewsModelItem) *ListDeepNewsModelResponse {
	this := ListDeepNewsModelResponse{}
	this.Models = models
	return &this
}

// NewListDeepNewsModelResponseWithDefaults instantiates a new ListDeepNewsModelResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDeepNewsModelResponseWithDefaults() *ListDeepNewsModelResponse {
	this := ListDeepNewsModelResponse{}
	return &this
}

// GetModels returns the Models field value
func (o *ListDeepNewsModelResponse) GetModels() []DeepNewsModelItem {
	if o == nil {
		var ret []DeepNewsModelItem
		return ret
	}

	return o.Models
}

// GetModelsOk returns a tuple with the Models field value
// and a boolean to check if the value has been set.
func (o *ListDeepNewsModelResponse) GetModelsOk() ([]DeepNewsModelItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Models, true
}

// SetModels sets field value
func (o *ListDeepNewsModelResponse) SetModels(v []DeepNewsModelItem) {
	o.Models = v
}

func (o ListDeepNewsModelResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDeepNewsModelResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["models"] = o.Models

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListDeepNewsModelResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"models",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListDeepNewsModelResponse := _ListDeepNewsModelResponse{}

	err = json.Unmarshal(data, &varListDeepNewsModelResponse)

	if err != nil {
		return err
	}

	*o = ListDeepNewsModelResponse(varListDeepNewsModelResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "models")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListDeepNewsModelResponse struct {
	value *ListDeepNewsModelResponse
	isSet bool
}

func (v NullableListDeepNewsModelResponse) Get() *ListDeepNewsModelResponse {
	return v.value
}

func (v *NullableListDeepNewsModelResponse) Set(val *ListDeepNewsModelResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListDeepNewsModelResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListDeepNewsModelResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDeepNewsModelResponse(val *ListDeepNewsModelResponse) *NullableListDeepNewsModelResponse {
	return &NullableListDeepNewsModelResponse{value: val, isSet: true}
}

func (v NullableListDeepNewsModelResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDeepNewsModelResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


