/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.28
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"time"
)

// checks if the UpdateNewsletterRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateNewsletterRequest{}

// UpdateNewsletterRequest struct for UpdateNewsletterRequest
type UpdateNewsletterRequest struct {
	Name NullableString `json:"name,omitempty"`
	Query NullableString `json:"query,omitempty"`
	Cron NullableString `json:"cron,omitempty"`
	Model NullableString `json:"model,omitempty"`
	Subject NullableString `json:"subject,omitempty"`
	Sender NullableString `json:"sender,omitempty"`
	LogoUrl NullableString `json:"logo_url,omitempty"`
	ReplyTo NullableString `json:"reply_to,omitempty"`
	AudienceId NullableString `json:"audience_id,omitempty"`
	ResendApiKey NullableString `json:"resend_api_key,omitempty"`
	Public NullableBool `json:"public,omitempty"`
	Active NullableBool `json:"active,omitempty"`
	ExpiresAt NullableTime `json:"expires_at,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateNewsletterRequest UpdateNewsletterRequest

// NewUpdateNewsletterRequest instantiates a new UpdateNewsletterRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateNewsletterRequest() *UpdateNewsletterRequest {
	this := UpdateNewsletterRequest{}
	return &this
}

// NewUpdateNewsletterRequestWithDefaults instantiates a new UpdateNewsletterRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNewsletterRequestWithDefaults() *UpdateNewsletterRequest {
	this := UpdateNewsletterRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNewsletterRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNewsletterRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *UpdateNewsletterRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *UpdateNewsletterRequest) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *UpdateNewsletterRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *UpdateNewsletterRequest) UnsetName() {
	o.Name.Unset()
}

// GetQuery returns the Query field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNewsletterRequest) GetQuery() string {
	if o == nil || IsNil(o.Query.Get()) {
		var ret string
		return ret
	}
	return *o.Query.Get()
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNewsletterRequest) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Query.Get(), o.Query.IsSet()
}

// HasQuery returns a boolean if a field has been set.
func (o *UpdateNewsletterRequest) HasQuery() bool {
	if o != nil && o.Query.IsSet() {
		return true
	}

	return false
}

// SetQuery gets a reference to the given NullableString and assigns it to the Query field.
func (o *UpdateNewsletterRequest) SetQuery(v string) {
	o.Query.Set(&v)
}
// SetQueryNil sets the value for Query to be an explicit nil
func (o *UpdateNewsletterRequest) SetQueryNil() {
	o.Query.Set(nil)
}

// UnsetQuery ensures that no value is present for Query, not even an explicit nil
func (o *UpdateNewsletterRequest) UnsetQuery() {
	o.Query.Unset()
}

// GetCron returns the Cron field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNewsletterRequest) GetCron() string {
	if o == nil || IsNil(o.Cron.Get()) {
		var ret string
		return ret
	}
	return *o.Cron.Get()
}

// GetCronOk returns a tuple with the Cron field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNewsletterRequest) GetCronOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cron.Get(), o.Cron.IsSet()
}

// HasCron returns a boolean if a field has been set.
func (o *UpdateNewsletterRequest) HasCron() bool {
	if o != nil && o.Cron.IsSet() {
		return true
	}

	return false
}

// SetCron gets a reference to the given NullableString and assigns it to the Cron field.
func (o *UpdateNewsletterRequest) SetCron(v string) {
	o.Cron.Set(&v)
}
// SetCronNil sets the value for Cron to be an explicit nil
func (o *UpdateNewsletterRequest) SetCronNil() {
	o.Cron.Set(nil)
}

// UnsetCron ensures that no value is present for Cron, not even an explicit nil
func (o *UpdateNewsletterRequest) UnsetCron() {
	o.Cron.Unset()
}

// GetModel returns the Model field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNewsletterRequest) GetModel() string {
	if o == nil || IsNil(o.Model.Get()) {
		var ret string
		return ret
	}
	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNewsletterRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// HasModel returns a boolean if a field has been set.
func (o *UpdateNewsletterRequest) HasModel() bool {
	if o != nil && o.Model.IsSet() {
		return true
	}

	return false
}

// SetModel gets a reference to the given NullableString and assigns it to the Model field.
func (o *UpdateNewsletterRequest) SetModel(v string) {
	o.Model.Set(&v)
}
// SetModelNil sets the value for Model to be an explicit nil
func (o *UpdateNewsletterRequest) SetModelNil() {
	o.Model.Set(nil)
}

// UnsetModel ensures that no value is present for Model, not even an explicit nil
func (o *UpdateNewsletterRequest) UnsetModel() {
	o.Model.Unset()
}

// GetSubject returns the Subject field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNewsletterRequest) GetSubject() string {
	if o == nil || IsNil(o.Subject.Get()) {
		var ret string
		return ret
	}
	return *o.Subject.Get()
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNewsletterRequest) GetSubjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subject.Get(), o.Subject.IsSet()
}

// HasSubject returns a boolean if a field has been set.
func (o *UpdateNewsletterRequest) HasSubject() bool {
	if o != nil && o.Subject.IsSet() {
		return true
	}

	return false
}

// SetSubject gets a reference to the given NullableString and assigns it to the Subject field.
func (o *UpdateNewsletterRequest) SetSubject(v string) {
	o.Subject.Set(&v)
}
// SetSubjectNil sets the value for Subject to be an explicit nil
func (o *UpdateNewsletterRequest) SetSubjectNil() {
	o.Subject.Set(nil)
}

// UnsetSubject ensures that no value is present for Subject, not even an explicit nil
func (o *UpdateNewsletterRequest) UnsetSubject() {
	o.Subject.Unset()
}

// GetSender returns the Sender field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNewsletterRequest) GetSender() string {
	if o == nil || IsNil(o.Sender.Get()) {
		var ret string
		return ret
	}
	return *o.Sender.Get()
}

// GetSenderOk returns a tuple with the Sender field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNewsletterRequest) GetSenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sender.Get(), o.Sender.IsSet()
}

// HasSender returns a boolean if a field has been set.
func (o *UpdateNewsletterRequest) HasSender() bool {
	if o != nil && o.Sender.IsSet() {
		return true
	}

	return false
}

// SetSender gets a reference to the given NullableString and assigns it to the Sender field.
func (o *UpdateNewsletterRequest) SetSender(v string) {
	o.Sender.Set(&v)
}
// SetSenderNil sets the value for Sender to be an explicit nil
func (o *UpdateNewsletterRequest) SetSenderNil() {
	o.Sender.Set(nil)
}

// UnsetSender ensures that no value is present for Sender, not even an explicit nil
func (o *UpdateNewsletterRequest) UnsetSender() {
	o.Sender.Unset()
}

// GetLogoUrl returns the LogoUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNewsletterRequest) GetLogoUrl() string {
	if o == nil || IsNil(o.LogoUrl.Get()) {
		var ret string
		return ret
	}
	return *o.LogoUrl.Get()
}

// GetLogoUrlOk returns a tuple with the LogoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNewsletterRequest) GetLogoUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogoUrl.Get(), o.LogoUrl.IsSet()
}

// HasLogoUrl returns a boolean if a field has been set.
func (o *UpdateNewsletterRequest) HasLogoUrl() bool {
	if o != nil && o.LogoUrl.IsSet() {
		return true
	}

	return false
}

// SetLogoUrl gets a reference to the given NullableString and assigns it to the LogoUrl field.
func (o *UpdateNewsletterRequest) SetLogoUrl(v string) {
	o.LogoUrl.Set(&v)
}
// SetLogoUrlNil sets the value for LogoUrl to be an explicit nil
func (o *UpdateNewsletterRequest) SetLogoUrlNil() {
	o.LogoUrl.Set(nil)
}

// UnsetLogoUrl ensures that no value is present for LogoUrl, not even an explicit nil
func (o *UpdateNewsletterRequest) UnsetLogoUrl() {
	o.LogoUrl.Unset()
}

// GetReplyTo returns the ReplyTo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNewsletterRequest) GetReplyTo() string {
	if o == nil || IsNil(o.ReplyTo.Get()) {
		var ret string
		return ret
	}
	return *o.ReplyTo.Get()
}

// GetReplyToOk returns a tuple with the ReplyTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNewsletterRequest) GetReplyToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReplyTo.Get(), o.ReplyTo.IsSet()
}

// HasReplyTo returns a boolean if a field has been set.
func (o *UpdateNewsletterRequest) HasReplyTo() bool {
	if o != nil && o.ReplyTo.IsSet() {
		return true
	}

	return false
}

// SetReplyTo gets a reference to the given NullableString and assigns it to the ReplyTo field.
func (o *UpdateNewsletterRequest) SetReplyTo(v string) {
	o.ReplyTo.Set(&v)
}
// SetReplyToNil sets the value for ReplyTo to be an explicit nil
func (o *UpdateNewsletterRequest) SetReplyToNil() {
	o.ReplyTo.Set(nil)
}

// UnsetReplyTo ensures that no value is present for ReplyTo, not even an explicit nil
func (o *UpdateNewsletterRequest) UnsetReplyTo() {
	o.ReplyTo.Unset()
}

// GetAudienceId returns the AudienceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNewsletterRequest) GetAudienceId() string {
	if o == nil || IsNil(o.AudienceId.Get()) {
		var ret string
		return ret
	}
	return *o.AudienceId.Get()
}

// GetAudienceIdOk returns a tuple with the AudienceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNewsletterRequest) GetAudienceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AudienceId.Get(), o.AudienceId.IsSet()
}

// HasAudienceId returns a boolean if a field has been set.
func (o *UpdateNewsletterRequest) HasAudienceId() bool {
	if o != nil && o.AudienceId.IsSet() {
		return true
	}

	return false
}

// SetAudienceId gets a reference to the given NullableString and assigns it to the AudienceId field.
func (o *UpdateNewsletterRequest) SetAudienceId(v string) {
	o.AudienceId.Set(&v)
}
// SetAudienceIdNil sets the value for AudienceId to be an explicit nil
func (o *UpdateNewsletterRequest) SetAudienceIdNil() {
	o.AudienceId.Set(nil)
}

// UnsetAudienceId ensures that no value is present for AudienceId, not even an explicit nil
func (o *UpdateNewsletterRequest) UnsetAudienceId() {
	o.AudienceId.Unset()
}

// GetResendApiKey returns the ResendApiKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNewsletterRequest) GetResendApiKey() string {
	if o == nil || IsNil(o.ResendApiKey.Get()) {
		var ret string
		return ret
	}
	return *o.ResendApiKey.Get()
}

// GetResendApiKeyOk returns a tuple with the ResendApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNewsletterRequest) GetResendApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResendApiKey.Get(), o.ResendApiKey.IsSet()
}

// HasResendApiKey returns a boolean if a field has been set.
func (o *UpdateNewsletterRequest) HasResendApiKey() bool {
	if o != nil && o.ResendApiKey.IsSet() {
		return true
	}

	return false
}

// SetResendApiKey gets a reference to the given NullableString and assigns it to the ResendApiKey field.
func (o *UpdateNewsletterRequest) SetResendApiKey(v string) {
	o.ResendApiKey.Set(&v)
}
// SetResendApiKeyNil sets the value for ResendApiKey to be an explicit nil
func (o *UpdateNewsletterRequest) SetResendApiKeyNil() {
	o.ResendApiKey.Set(nil)
}

// UnsetResendApiKey ensures that no value is present for ResendApiKey, not even an explicit nil
func (o *UpdateNewsletterRequest) UnsetResendApiKey() {
	o.ResendApiKey.Unset()
}

// GetPublic returns the Public field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNewsletterRequest) GetPublic() bool {
	if o == nil || IsNil(o.Public.Get()) {
		var ret bool
		return ret
	}
	return *o.Public.Get()
}

// GetPublicOk returns a tuple with the Public field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNewsletterRequest) GetPublicOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Public.Get(), o.Public.IsSet()
}

// HasPublic returns a boolean if a field has been set.
func (o *UpdateNewsletterRequest) HasPublic() bool {
	if o != nil && o.Public.IsSet() {
		return true
	}

	return false
}

// SetPublic gets a reference to the given NullableBool and assigns it to the Public field.
func (o *UpdateNewsletterRequest) SetPublic(v bool) {
	o.Public.Set(&v)
}
// SetPublicNil sets the value for Public to be an explicit nil
func (o *UpdateNewsletterRequest) SetPublicNil() {
	o.Public.Set(nil)
}

// UnsetPublic ensures that no value is present for Public, not even an explicit nil
func (o *UpdateNewsletterRequest) UnsetPublic() {
	o.Public.Unset()
}

// GetActive returns the Active field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNewsletterRequest) GetActive() bool {
	if o == nil || IsNil(o.Active.Get()) {
		var ret bool
		return ret
	}
	return *o.Active.Get()
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNewsletterRequest) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Active.Get(), o.Active.IsSet()
}

// HasActive returns a boolean if a field has been set.
func (o *UpdateNewsletterRequest) HasActive() bool {
	if o != nil && o.Active.IsSet() {
		return true
	}

	return false
}

// SetActive gets a reference to the given NullableBool and assigns it to the Active field.
func (o *UpdateNewsletterRequest) SetActive(v bool) {
	o.Active.Set(&v)
}
// SetActiveNil sets the value for Active to be an explicit nil
func (o *UpdateNewsletterRequest) SetActiveNil() {
	o.Active.Set(nil)
}

// UnsetActive ensures that no value is present for Active, not even an explicit nil
func (o *UpdateNewsletterRequest) UnsetActive() {
	o.Active.Unset()
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNewsletterRequest) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNewsletterRequest) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *UpdateNewsletterRequest) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableTime and assigns it to the ExpiresAt field.
func (o *UpdateNewsletterRequest) SetExpiresAt(v time.Time) {
	o.ExpiresAt.Set(&v)
}
// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *UpdateNewsletterRequest) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *UpdateNewsletterRequest) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

func (o UpdateNewsletterRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateNewsletterRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Query.IsSet() {
		toSerialize["query"] = o.Query.Get()
	}
	if o.Cron.IsSet() {
		toSerialize["cron"] = o.Cron.Get()
	}
	if o.Model.IsSet() {
		toSerialize["model"] = o.Model.Get()
	}
	if o.Subject.IsSet() {
		toSerialize["subject"] = o.Subject.Get()
	}
	if o.Sender.IsSet() {
		toSerialize["sender"] = o.Sender.Get()
	}
	if o.LogoUrl.IsSet() {
		toSerialize["logo_url"] = o.LogoUrl.Get()
	}
	if o.ReplyTo.IsSet() {
		toSerialize["reply_to"] = o.ReplyTo.Get()
	}
	if o.AudienceId.IsSet() {
		toSerialize["audience_id"] = o.AudienceId.Get()
	}
	if o.ResendApiKey.IsSet() {
		toSerialize["resend_api_key"] = o.ResendApiKey.Get()
	}
	if o.Public.IsSet() {
		toSerialize["public"] = o.Public.Get()
	}
	if o.Active.IsSet() {
		toSerialize["active"] = o.Active.Get()
	}
	if o.ExpiresAt.IsSet() {
		toSerialize["expires_at"] = o.ExpiresAt.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateNewsletterRequest) UnmarshalJSON(data []byte) (err error) {
	varUpdateNewsletterRequest := _UpdateNewsletterRequest{}

	err = json.Unmarshal(data, &varUpdateNewsletterRequest)

	if err != nil {
		return err
	}

	*o = UpdateNewsletterRequest(varUpdateNewsletterRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "query")
		delete(additionalProperties, "cron")
		delete(additionalProperties, "model")
		delete(additionalProperties, "subject")
		delete(additionalProperties, "sender")
		delete(additionalProperties, "logo_url")
		delete(additionalProperties, "reply_to")
		delete(additionalProperties, "audience_id")
		delete(additionalProperties, "resend_api_key")
		delete(additionalProperties, "public")
		delete(additionalProperties, "active")
		delete(additionalProperties, "expires_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateNewsletterRequest struct {
	value *UpdateNewsletterRequest
	isSet bool
}

func (v NullableUpdateNewsletterRequest) Get() *UpdateNewsletterRequest {
	return v.value
}

func (v *NullableUpdateNewsletterRequest) Set(val *UpdateNewsletterRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNewsletterRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNewsletterRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNewsletterRequest(val *UpdateNewsletterRequest) *NullableUpdateNewsletterRequest {
	return &NullableUpdateNewsletterRequest{value: val, isSet: true}
}

func (v NullableUpdateNewsletterRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNewsletterRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


