/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.22
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)


// Source struct for Source
type Source struct {
	CreateDeepNewsResponseStreamSourcesChartSource *CreateDeepNewsResponseStreamSourcesChartSource
	CreateDeepNewsResponseStreamSourcesGraphSource *CreateDeepNewsResponseStreamSourcesGraphSource
	CreateDeepNewsResponseStreamSourcesNewsSource *CreateDeepNewsResponseStreamSourcesNewsSource
	CreateDeepNewsResponseStreamSourcesWebSource *CreateDeepNewsResponseStreamSourcesWebSource
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Source) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into CreateDeepNewsResponseStreamSourcesChartSource
	err = json.Unmarshal(data, &dst.CreateDeepNewsResponseStreamSourcesChartSource);
	if err == nil {
		jsonCreateDeepNewsResponseStreamSourcesChartSource, _ := json.Marshal(dst.CreateDeepNewsResponseStreamSourcesChartSource)
		if string(jsonCreateDeepNewsResponseStreamSourcesChartSource) == "{}" { // empty struct
			dst.CreateDeepNewsResponseStreamSourcesChartSource = nil
		} else {
			return nil // data stored in dst.CreateDeepNewsResponseStreamSourcesChartSource, return on the first match
		}
	} else {
		dst.CreateDeepNewsResponseStreamSourcesChartSource = nil
	}

	// try to unmarshal JSON data into CreateDeepNewsResponseStreamSourcesGraphSource
	err = json.Unmarshal(data, &dst.CreateDeepNewsResponseStreamSourcesGraphSource);
	if err == nil {
		jsonCreateDeepNewsResponseStreamSourcesGraphSource, _ := json.Marshal(dst.CreateDeepNewsResponseStreamSourcesGraphSource)
		if string(jsonCreateDeepNewsResponseStreamSourcesGraphSource) == "{}" { // empty struct
			dst.CreateDeepNewsResponseStreamSourcesGraphSource = nil
		} else {
			return nil // data stored in dst.CreateDeepNewsResponseStreamSourcesGraphSource, return on the first match
		}
	} else {
		dst.CreateDeepNewsResponseStreamSourcesGraphSource = nil
	}

	// try to unmarshal JSON data into CreateDeepNewsResponseStreamSourcesNewsSource
	err = json.Unmarshal(data, &dst.CreateDeepNewsResponseStreamSourcesNewsSource);
	if err == nil {
		jsonCreateDeepNewsResponseStreamSourcesNewsSource, _ := json.Marshal(dst.CreateDeepNewsResponseStreamSourcesNewsSource)
		if string(jsonCreateDeepNewsResponseStreamSourcesNewsSource) == "{}" { // empty struct
			dst.CreateDeepNewsResponseStreamSourcesNewsSource = nil
		} else {
			return nil // data stored in dst.CreateDeepNewsResponseStreamSourcesNewsSource, return on the first match
		}
	} else {
		dst.CreateDeepNewsResponseStreamSourcesNewsSource = nil
	}

	// try to unmarshal JSON data into CreateDeepNewsResponseStreamSourcesWebSource
	err = json.Unmarshal(data, &dst.CreateDeepNewsResponseStreamSourcesWebSource);
	if err == nil {
		jsonCreateDeepNewsResponseStreamSourcesWebSource, _ := json.Marshal(dst.CreateDeepNewsResponseStreamSourcesWebSource)
		if string(jsonCreateDeepNewsResponseStreamSourcesWebSource) == "{}" { // empty struct
			dst.CreateDeepNewsResponseStreamSourcesWebSource = nil
		} else {
			return nil // data stored in dst.CreateDeepNewsResponseStreamSourcesWebSource, return on the first match
		}
	} else {
		dst.CreateDeepNewsResponseStreamSourcesWebSource = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Source)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Source) MarshalJSON() ([]byte, error) {
	if src.CreateDeepNewsResponseStreamSourcesChartSource != nil {
		return json.Marshal(&src.CreateDeepNewsResponseStreamSourcesChartSource)
	}

	if src.CreateDeepNewsResponseStreamSourcesGraphSource != nil {
		return json.Marshal(&src.CreateDeepNewsResponseStreamSourcesGraphSource)
	}

	if src.CreateDeepNewsResponseStreamSourcesNewsSource != nil {
		return json.Marshal(&src.CreateDeepNewsResponseStreamSourcesNewsSource)
	}

	if src.CreateDeepNewsResponseStreamSourcesWebSource != nil {
		return json.Marshal(&src.CreateDeepNewsResponseStreamSourcesWebSource)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableSource struct {
	value *Source
	isSet bool
}

func (v NullableSource) Get() *Source {
	return v.value
}

func (v *NullableSource) Set(val *Source) {
	v.value = val
	v.isSet = true
}

func (v NullableSource) IsSet() bool {
	return v.isSet
}

func (v *NullableSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSource(val *Source) *NullableSource {
	return &NullableSource{value: val, isSet: true}
}

func (v NullableSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


