/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.27
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)


// BadDomainUrl2 Domain blacklist.This can be a single domain or a list of domains. For example, 'npr.org' or ['nature.com', 'npr.org']
type BadDomainUrl2 struct {
	ArrayOfString *[]string
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *BadDomainUrl2) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into ArrayOfString
	err = json.Unmarshal(data, &dst.ArrayOfString);
	if err == nil {
		jsonArrayOfString, _ := json.Marshal(dst.ArrayOfString)
		if string(jsonArrayOfString) == "{}" { // empty struct
			dst.ArrayOfString = nil
		} else {
			return nil // data stored in dst.ArrayOfString, return on the first match
		}
	} else {
		dst.ArrayOfString = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(BadDomainUrl2)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BadDomainUrl2) MarshalJSON() ([]byte, error) {
	if src.ArrayOfString != nil {
		return json.Marshal(&src.ArrayOfString)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableBadDomainUrl2 struct {
	value *BadDomainUrl2
	isSet bool
}

func (v NullableBadDomainUrl2) Get() *BadDomainUrl2 {
	return v.value
}

func (v *NullableBadDomainUrl2) Set(val *BadDomainUrl2) {
	v.value = val
	v.isSet = true
}

func (v NullableBadDomainUrl2) IsSet() bool {
	return v.isSet
}

func (v *NullableBadDomainUrl2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBadDomainUrl2(val *BadDomainUrl2) *NullableBadDomainUrl2 {
	return &NullableBadDomainUrl2{value: val, isSet: true}
}

func (v NullableBadDomainUrl2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBadDomainUrl2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


