/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.22
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the ScrapeItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScrapeItem{}

// ScrapeItem struct for ScrapeItem
type ScrapeItem struct {
	UserAgent string `json:"user_agent"`
	Count int32 `json:"count"`
	AdditionalProperties map[string]interface{}
}

type _ScrapeItem ScrapeItem

// NewScrapeItem instantiates a new ScrapeItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScrapeItem(userAgent string, count int32) *ScrapeItem {
	this := ScrapeItem{}
	this.UserAgent = userAgent
	this.Count = count
	return &this
}

// NewScrapeItemWithDefaults instantiates a new ScrapeItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScrapeItemWithDefaults() *ScrapeItem {
	this := ScrapeItem{}
	return &this
}

// GetUserAgent returns the UserAgent field value
func (o *ScrapeItem) GetUserAgent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserAgent
}

// GetUserAgentOk returns a tuple with the UserAgent field value
// and a boolean to check if the value has been set.
func (o *ScrapeItem) GetUserAgentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserAgent, true
}

// SetUserAgent sets field value
func (o *ScrapeItem) SetUserAgent(v string) {
	o.UserAgent = v
}

// GetCount returns the Count field value
func (o *ScrapeItem) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *ScrapeItem) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *ScrapeItem) SetCount(v int32) {
	o.Count = v
}

func (o ScrapeItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScrapeItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_agent"] = o.UserAgent
	toSerialize["count"] = o.Count

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ScrapeItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_agent",
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScrapeItem := _ScrapeItem{}

	err = json.Unmarshal(data, &varScrapeItem)

	if err != nil {
		return err
	}

	*o = ScrapeItem(varScrapeItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "user_agent")
		delete(additionalProperties, "count")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableScrapeItem struct {
	value *ScrapeItem
	isSet bool
}

func (v NullableScrapeItem) Get() *ScrapeItem {
	return v.value
}

func (v *NullableScrapeItem) Set(val *ScrapeItem) {
	v.value = val
	v.isSet = true
}

func (v NullableScrapeItem) IsSet() bool {
	return v.isSet
}

func (v *NullableScrapeItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScrapeItem(val *ScrapeItem) *NullableScrapeItem {
	return &NullableScrapeItem{value: val, isSet: true}
}

func (v NullableScrapeItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScrapeItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


