/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.22
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
)

// checks if the RedditEntities type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RedditEntities{}

// RedditEntities struct for RedditEntities
type RedditEntities struct {
	DATE []string `json:"DATE,omitempty"`
	EVENT []string `json:"EVENT,omitempty"`
	GPE []string `json:"GPE,omitempty"`
	ORG []string `json:"ORG,omitempty"`
	PERSON []string `json:"PERSON,omitempty"`
	NORP []string `json:"NORP,omitempty"`
	CARDINAL []string `json:"CARDINAL,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RedditEntities RedditEntities

// NewRedditEntities instantiates a new RedditEntities object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRedditEntities() *RedditEntities {
	this := RedditEntities{}
	return &this
}

// NewRedditEntitiesWithDefaults instantiates a new RedditEntities object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRedditEntitiesWithDefaults() *RedditEntities {
	this := RedditEntities{}
	return &this
}

// GetDATE returns the DATE field value if set, zero value otherwise.
func (o *RedditEntities) GetDATE() []string {
	if o == nil || IsNil(o.DATE) {
		var ret []string
		return ret
	}
	return o.DATE
}

// GetDATEOk returns a tuple with the DATE field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RedditEntities) GetDATEOk() ([]string, bool) {
	if o == nil || IsNil(o.DATE) {
		return nil, false
	}
	return o.DATE, true
}

// HasDATE returns a boolean if a field has been set.
func (o *RedditEntities) HasDATE() bool {
	if o != nil && !IsNil(o.DATE) {
		return true
	}

	return false
}

// SetDATE gets a reference to the given []string and assigns it to the DATE field.
func (o *RedditEntities) SetDATE(v []string) {
	o.DATE = v
}

// GetEVENT returns the EVENT field value if set, zero value otherwise.
func (o *RedditEntities) GetEVENT() []string {
	if o == nil || IsNil(o.EVENT) {
		var ret []string
		return ret
	}
	return o.EVENT
}

// GetEVENTOk returns a tuple with the EVENT field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RedditEntities) GetEVENTOk() ([]string, bool) {
	if o == nil || IsNil(o.EVENT) {
		return nil, false
	}
	return o.EVENT, true
}

// HasEVENT returns a boolean if a field has been set.
func (o *RedditEntities) HasEVENT() bool {
	if o != nil && !IsNil(o.EVENT) {
		return true
	}

	return false
}

// SetEVENT gets a reference to the given []string and assigns it to the EVENT field.
func (o *RedditEntities) SetEVENT(v []string) {
	o.EVENT = v
}

// GetGPE returns the GPE field value if set, zero value otherwise.
func (o *RedditEntities) GetGPE() []string {
	if o == nil || IsNil(o.GPE) {
		var ret []string
		return ret
	}
	return o.GPE
}

// GetGPEOk returns a tuple with the GPE field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RedditEntities) GetGPEOk() ([]string, bool) {
	if o == nil || IsNil(o.GPE) {
		return nil, false
	}
	return o.GPE, true
}

// HasGPE returns a boolean if a field has been set.
func (o *RedditEntities) HasGPE() bool {
	if o != nil && !IsNil(o.GPE) {
		return true
	}

	return false
}

// SetGPE gets a reference to the given []string and assigns it to the GPE field.
func (o *RedditEntities) SetGPE(v []string) {
	o.GPE = v
}

// GetORG returns the ORG field value if set, zero value otherwise.
func (o *RedditEntities) GetORG() []string {
	if o == nil || IsNil(o.ORG) {
		var ret []string
		return ret
	}
	return o.ORG
}

// GetORGOk returns a tuple with the ORG field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RedditEntities) GetORGOk() ([]string, bool) {
	if o == nil || IsNil(o.ORG) {
		return nil, false
	}
	return o.ORG, true
}

// HasORG returns a boolean if a field has been set.
func (o *RedditEntities) HasORG() bool {
	if o != nil && !IsNil(o.ORG) {
		return true
	}

	return false
}

// SetORG gets a reference to the given []string and assigns it to the ORG field.
func (o *RedditEntities) SetORG(v []string) {
	o.ORG = v
}

// GetPERSON returns the PERSON field value if set, zero value otherwise.
func (o *RedditEntities) GetPERSON() []string {
	if o == nil || IsNil(o.PERSON) {
		var ret []string
		return ret
	}
	return o.PERSON
}

// GetPERSONOk returns a tuple with the PERSON field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RedditEntities) GetPERSONOk() ([]string, bool) {
	if o == nil || IsNil(o.PERSON) {
		return nil, false
	}
	return o.PERSON, true
}

// HasPERSON returns a boolean if a field has been set.
func (o *RedditEntities) HasPERSON() bool {
	if o != nil && !IsNil(o.PERSON) {
		return true
	}

	return false
}

// SetPERSON gets a reference to the given []string and assigns it to the PERSON field.
func (o *RedditEntities) SetPERSON(v []string) {
	o.PERSON = v
}

// GetNORP returns the NORP field value if set, zero value otherwise.
func (o *RedditEntities) GetNORP() []string {
	if o == nil || IsNil(o.NORP) {
		var ret []string
		return ret
	}
	return o.NORP
}

// GetNORPOk returns a tuple with the NORP field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RedditEntities) GetNORPOk() ([]string, bool) {
	if o == nil || IsNil(o.NORP) {
		return nil, false
	}
	return o.NORP, true
}

// HasNORP returns a boolean if a field has been set.
func (o *RedditEntities) HasNORP() bool {
	if o != nil && !IsNil(o.NORP) {
		return true
	}

	return false
}

// SetNORP gets a reference to the given []string and assigns it to the NORP field.
func (o *RedditEntities) SetNORP(v []string) {
	o.NORP = v
}

// GetCARDINAL returns the CARDINAL field value if set, zero value otherwise.
func (o *RedditEntities) GetCARDINAL() []string {
	if o == nil || IsNil(o.CARDINAL) {
		var ret []string
		return ret
	}
	return o.CARDINAL
}

// GetCARDINALOk returns a tuple with the CARDINAL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RedditEntities) GetCARDINALOk() ([]string, bool) {
	if o == nil || IsNil(o.CARDINAL) {
		return nil, false
	}
	return o.CARDINAL, true
}

// HasCARDINAL returns a boolean if a field has been set.
func (o *RedditEntities) HasCARDINAL() bool {
	if o != nil && !IsNil(o.CARDINAL) {
		return true
	}

	return false
}

// SetCARDINAL gets a reference to the given []string and assigns it to the CARDINAL field.
func (o *RedditEntities) SetCARDINAL(v []string) {
	o.CARDINAL = v
}

func (o RedditEntities) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RedditEntities) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DATE) {
		toSerialize["DATE"] = o.DATE
	}
	if !IsNil(o.EVENT) {
		toSerialize["EVENT"] = o.EVENT
	}
	if !IsNil(o.GPE) {
		toSerialize["GPE"] = o.GPE
	}
	if !IsNil(o.ORG) {
		toSerialize["ORG"] = o.ORG
	}
	if !IsNil(o.PERSON) {
		toSerialize["PERSON"] = o.PERSON
	}
	if !IsNil(o.NORP) {
		toSerialize["NORP"] = o.NORP
	}
	if !IsNil(o.CARDINAL) {
		toSerialize["CARDINAL"] = o.CARDINAL
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RedditEntities) UnmarshalJSON(data []byte) (err error) {
	varRedditEntities := _RedditEntities{}

	err = json.Unmarshal(data, &varRedditEntities)

	if err != nil {
		return err
	}

	*o = RedditEntities(varRedditEntities)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "DATE")
		delete(additionalProperties, "EVENT")
		delete(additionalProperties, "GPE")
		delete(additionalProperties, "ORG")
		delete(additionalProperties, "PERSON")
		delete(additionalProperties, "NORP")
		delete(additionalProperties, "CARDINAL")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRedditEntities struct {
	value *RedditEntities
	isSet bool
}

func (v NullableRedditEntities) Get() *RedditEntities {
	return v.value
}

func (v *NullableRedditEntities) Set(val *RedditEntities) {
	v.value = val
	v.isSet = true
}

func (v NullableRedditEntities) IsSet() bool {
	return v.isSet
}

func (v *NullableRedditEntities) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRedditEntities(val *RedditEntities) *NullableRedditEntities {
	return &NullableRedditEntities{value: val, isSet: true}
}

func (v NullableRedditEntities) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRedditEntities) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


