/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.28
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
)

// checks if the ReportRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReportRequest{}

// ReportRequest struct for ReportRequest
type ReportRequest struct {
	Prompt [][]string `json:"prompt,omitempty"`
	Model NullableString `json:"model,omitempty"`
	LogoUrl NullableString `json:"logo_url,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ReportRequest ReportRequest

// NewReportRequest instantiates a new ReportRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportRequest() *ReportRequest {
	this := ReportRequest{}
	return &this
}

// NewReportRequestWithDefaults instantiates a new ReportRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportRequestWithDefaults() *ReportRequest {
	this := ReportRequest{}
	return &this
}

// GetPrompt returns the Prompt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReportRequest) GetPrompt() [][]string {
	if o == nil {
		var ret [][]string
		return ret
	}
	return o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReportRequest) GetPromptOk() ([][]string, bool) {
	if o == nil || IsNil(o.Prompt) {
		return nil, false
	}
	return o.Prompt, true
}

// HasPrompt returns a boolean if a field has been set.
func (o *ReportRequest) HasPrompt() bool {
	if o != nil && !IsNil(o.Prompt) {
		return true
	}

	return false
}

// SetPrompt gets a reference to the given [][]string and assigns it to the Prompt field.
func (o *ReportRequest) SetPrompt(v [][]string) {
	o.Prompt = v
}

// GetModel returns the Model field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReportRequest) GetModel() string {
	if o == nil || IsNil(o.Model.Get()) {
		var ret string
		return ret
	}
	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReportRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// HasModel returns a boolean if a field has been set.
func (o *ReportRequest) HasModel() bool {
	if o != nil && o.Model.IsSet() {
		return true
	}

	return false
}

// SetModel gets a reference to the given NullableString and assigns it to the Model field.
func (o *ReportRequest) SetModel(v string) {
	o.Model.Set(&v)
}
// SetModelNil sets the value for Model to be an explicit nil
func (o *ReportRequest) SetModelNil() {
	o.Model.Set(nil)
}

// UnsetModel ensures that no value is present for Model, not even an explicit nil
func (o *ReportRequest) UnsetModel() {
	o.Model.Unset()
}

// GetLogoUrl returns the LogoUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReportRequest) GetLogoUrl() string {
	if o == nil || IsNil(o.LogoUrl.Get()) {
		var ret string
		return ret
	}
	return *o.LogoUrl.Get()
}

// GetLogoUrlOk returns a tuple with the LogoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReportRequest) GetLogoUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogoUrl.Get(), o.LogoUrl.IsSet()
}

// HasLogoUrl returns a boolean if a field has been set.
func (o *ReportRequest) HasLogoUrl() bool {
	if o != nil && o.LogoUrl.IsSet() {
		return true
	}

	return false
}

// SetLogoUrl gets a reference to the given NullableString and assigns it to the LogoUrl field.
func (o *ReportRequest) SetLogoUrl(v string) {
	o.LogoUrl.Set(&v)
}
// SetLogoUrlNil sets the value for LogoUrl to be an explicit nil
func (o *ReportRequest) SetLogoUrlNil() {
	o.LogoUrl.Set(nil)
}

// UnsetLogoUrl ensures that no value is present for LogoUrl, not even an explicit nil
func (o *ReportRequest) UnsetLogoUrl() {
	o.LogoUrl.Unset()
}

func (o ReportRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReportRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Prompt != nil {
		toSerialize["prompt"] = o.Prompt
	}
	if o.Model.IsSet() {
		toSerialize["model"] = o.Model.Get()
	}
	if o.LogoUrl.IsSet() {
		toSerialize["logo_url"] = o.LogoUrl.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReportRequest) UnmarshalJSON(data []byte) (err error) {
	varReportRequest := _ReportRequest{}

	err = json.Unmarshal(data, &varReportRequest)

	if err != nil {
		return err
	}

	*o = ReportRequest(varReportRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "prompt")
		delete(additionalProperties, "model")
		delete(additionalProperties, "logo_url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReportRequest struct {
	value *ReportRequest
	isSet bool
}

func (v NullableReportRequest) Get() *ReportRequest {
	return v.value
}

func (v *NullableReportRequest) Set(val *ReportRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableReportRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableReportRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportRequest(val *ReportRequest) *NullableReportRequest {
	return &NullableReportRequest{value: val, isSet: true}
}

func (v NullableReportRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


