/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.28
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the ScrapedURLItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScrapedURLItem{}

// ScrapedURLItem struct for ScrapedURLItem
type ScrapedURLItem struct {
	Url string `json:"url"`
	Data NullableScrapeDataItem `json:"data,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Enrichments map[string]interface{} `json:"enrichments,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ScrapedURLItem ScrapedURLItem

// NewScrapedURLItem instantiates a new ScrapedURLItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScrapedURLItem(url string) *ScrapedURLItem {
	this := ScrapedURLItem{}
	this.Url = url
	return &this
}

// NewScrapedURLItemWithDefaults instantiates a new ScrapedURLItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScrapedURLItemWithDefaults() *ScrapedURLItem {
	this := ScrapedURLItem{}
	return &this
}

// GetUrl returns the Url field value
func (o *ScrapedURLItem) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ScrapedURLItem) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ScrapedURLItem) SetUrl(v string) {
	o.Url = v
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScrapedURLItem) GetData() ScrapeDataItem {
	if o == nil || IsNil(o.Data.Get()) {
		var ret ScrapeDataItem
		return ret
	}
	return *o.Data.Get()
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScrapedURLItem) GetDataOk() (*ScrapeDataItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data.Get(), o.Data.IsSet()
}

// HasData returns a boolean if a field has been set.
func (o *ScrapedURLItem) HasData() bool {
	if o != nil && o.Data.IsSet() {
		return true
	}

	return false
}

// SetData gets a reference to the given NullableScrapeDataItem and assigns it to the Data field.
func (o *ScrapedURLItem) SetData(v ScrapeDataItem) {
	o.Data.Set(&v)
}
// SetDataNil sets the value for Data to be an explicit nil
func (o *ScrapedURLItem) SetDataNil() {
	o.Data.Set(nil)
}

// UnsetData ensures that no value is present for Data, not even an explicit nil
func (o *ScrapedURLItem) UnsetData() {
	o.Data.Unset()
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScrapedURLItem) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScrapedURLItem) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ScrapedURLItem) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *ScrapedURLItem) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetEnrichments returns the Enrichments field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScrapedURLItem) GetEnrichments() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Enrichments
}

// GetEnrichmentsOk returns a tuple with the Enrichments field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScrapedURLItem) GetEnrichmentsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Enrichments) {
		return map[string]interface{}{}, false
	}
	return o.Enrichments, true
}

// HasEnrichments returns a boolean if a field has been set.
func (o *ScrapedURLItem) HasEnrichments() bool {
	if o != nil && !IsNil(o.Enrichments) {
		return true
	}

	return false
}

// SetEnrichments gets a reference to the given map[string]interface{} and assigns it to the Enrichments field.
func (o *ScrapedURLItem) SetEnrichments(v map[string]interface{}) {
	o.Enrichments = v
}

func (o ScrapedURLItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScrapedURLItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	if o.Data.IsSet() {
		toSerialize["data"] = o.Data.Get()
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Enrichments != nil {
		toSerialize["enrichments"] = o.Enrichments
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ScrapedURLItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScrapedURLItem := _ScrapedURLItem{}

	err = json.Unmarshal(data, &varScrapedURLItem)

	if err != nil {
		return err
	}

	*o = ScrapedURLItem(varScrapedURLItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "url")
		delete(additionalProperties, "data")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "enrichments")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableScrapedURLItem struct {
	value *ScrapedURLItem
	isSet bool
}

func (v NullableScrapedURLItem) Get() *ScrapedURLItem {
	return v.value
}

func (v *NullableScrapedURLItem) Set(val *ScrapedURLItem) {
	v.value = val
	v.isSet = true
}

func (v NullableScrapedURLItem) IsSet() bool {
	return v.isSet
}

func (v *NullableScrapedURLItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScrapedURLItem(val *ScrapedURLItem) *NullableScrapedURLItem {
	return &NullableScrapedURLItem{value: val, isSet: true}
}

func (v NullableScrapedURLItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScrapedURLItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


