/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.28
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the EmailAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailAction{}

// EmailAction struct for EmailAction
type EmailAction struct {
	Action *string `json:"action,omitempty"`
	Params EmailParams `json:"params"`
	AdditionalProperties map[string]interface{}
}

type _EmailAction EmailAction

// NewEmailAction instantiates a new EmailAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailAction(params EmailParams) *EmailAction {
	this := EmailAction{}
	var action string = "email"
	this.Action = &action
	this.Params = params
	return &this
}

// NewEmailActionWithDefaults instantiates a new EmailAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailActionWithDefaults() *EmailAction {
	this := EmailAction{}
	var action string = "email"
	this.Action = &action
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *EmailAction) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailAction) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *EmailAction) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *EmailAction) SetAction(v string) {
	o.Action = &v
}

// GetParams returns the Params field value
func (o *EmailAction) GetParams() EmailParams {
	if o == nil {
		var ret EmailParams
		return ret
	}

	return o.Params
}

// GetParamsOk returns a tuple with the Params field value
// and a boolean to check if the value has been set.
func (o *EmailAction) GetParamsOk() (*EmailParams, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Params, true
}

// SetParams sets field value
func (o *EmailAction) SetParams(v EmailParams) {
	o.Params = v
}

func (o EmailAction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	toSerialize["params"] = o.Params

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EmailAction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"params",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailAction := _EmailAction{}

	err = json.Unmarshal(data, &varEmailAction)

	if err != nil {
		return err
	}

	*o = EmailAction(varEmailAction)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "action")
		delete(additionalProperties, "params")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEmailAction struct {
	value *EmailAction
	isSet bool
}

func (v NullableEmailAction) Get() *EmailAction {
	return v.value
}

func (v *NullableEmailAction) Set(val *EmailAction) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailAction) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailAction(val *EmailAction) *NullableEmailAction {
	return &NullableEmailAction{value: val, isSet: true}
}

func (v NullableEmailAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


