/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.28
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the NewsletterContactUpdateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewsletterContactUpdateResponse{}

// NewsletterContactUpdateResponse struct for NewsletterContactUpdateResponse
type NewsletterContactUpdateResponse struct {
	Id string `json:"id"`
	AdditionalProperties map[string]interface{}
}

type _NewsletterContactUpdateResponse NewsletterContactUpdateResponse

// NewNewsletterContactUpdateResponse instantiates a new NewsletterContactUpdateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewsletterContactUpdateResponse(id string) *NewsletterContactUpdateResponse {
	this := NewsletterContactUpdateResponse{}
	this.Id = id
	return &this
}

// NewNewsletterContactUpdateResponseWithDefaults instantiates a new NewsletterContactUpdateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewsletterContactUpdateResponseWithDefaults() *NewsletterContactUpdateResponse {
	this := NewsletterContactUpdateResponse{}
	return &this
}

// GetId returns the Id field value
func (o *NewsletterContactUpdateResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *NewsletterContactUpdateResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NewsletterContactUpdateResponse) SetId(v string) {
	o.Id = v
}

func (o NewsletterContactUpdateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewsletterContactUpdateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NewsletterContactUpdateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewsletterContactUpdateResponse := _NewsletterContactUpdateResponse{}

	err = json.Unmarshal(data, &varNewsletterContactUpdateResponse)

	if err != nil {
		return err
	}

	*o = NewsletterContactUpdateResponse(varNewsletterContactUpdateResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNewsletterContactUpdateResponse struct {
	value *NewsletterContactUpdateResponse
	isSet bool
}

func (v NullableNewsletterContactUpdateResponse) Get() *NewsletterContactUpdateResponse {
	return v.value
}

func (v *NullableNewsletterContactUpdateResponse) Set(val *NewsletterContactUpdateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNewsletterContactUpdateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNewsletterContactUpdateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewsletterContactUpdateResponse(val *NewsletterContactUpdateResponse) *NullableNewsletterContactUpdateResponse {
	return &NullableNewsletterContactUpdateResponse{value: val, isSet: true}
}

func (v NullableNewsletterContactUpdateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewsletterContactUpdateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


