/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.50
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
)

// checks if the LegacyReportRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LegacyReportRequest{}

// LegacyReportRequest Legacy report configuration (original format).  This is the original ReportRequest format that uses a simple model field for report generation without DeepNews capabilities.
type LegacyReportRequest struct {
	Prompt [][]string `json:"prompt,omitempty"`
	LogoUrl NullableString `json:"logo_url,omitempty"`
	IncludeAppendix NullableBool `json:"include_appendix,omitempty"`
	// Append 'Generated by AskNews AI' watermark
	AsknewsWatermark *bool `json:"asknews_watermark,omitempty"`
	Identifier *string `json:"identifier,omitempty"`
	// The model to use for the report. Defaults to claude-sonnet-4-5-20250929.
	Model *string `json:"model,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LegacyReportRequest LegacyReportRequest

// NewLegacyReportRequest instantiates a new LegacyReportRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLegacyReportRequest() *LegacyReportRequest {
	this := LegacyReportRequest{}
	var asknewsWatermark bool = true
	this.AsknewsWatermark = &asknewsWatermark
	var identifier string = "legacy"
	this.Identifier = &identifier
	var model string = "claude-sonnet-4-5-20250929"
	this.Model = &model
	return &this
}

// NewLegacyReportRequestWithDefaults instantiates a new LegacyReportRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLegacyReportRequestWithDefaults() *LegacyReportRequest {
	this := LegacyReportRequest{}
	var asknewsWatermark bool = true
	this.AsknewsWatermark = &asknewsWatermark
	var identifier string = "legacy"
	this.Identifier = &identifier
	var model string = "claude-sonnet-4-5-20250929"
	this.Model = &model
	return &this
}

// GetPrompt returns the Prompt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LegacyReportRequest) GetPrompt() [][]string {
	if o == nil {
		var ret [][]string
		return ret
	}
	return o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LegacyReportRequest) GetPromptOk() ([][]string, bool) {
	if o == nil || IsNil(o.Prompt) {
		return nil, false
	}
	return o.Prompt, true
}

// HasPrompt returns a boolean if a field has been set.
func (o *LegacyReportRequest) HasPrompt() bool {
	if o != nil && !IsNil(o.Prompt) {
		return true
	}

	return false
}

// SetPrompt gets a reference to the given [][]string and assigns it to the Prompt field.
func (o *LegacyReportRequest) SetPrompt(v [][]string) {
	o.Prompt = v
}

// GetLogoUrl returns the LogoUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LegacyReportRequest) GetLogoUrl() string {
	if o == nil || IsNil(o.LogoUrl.Get()) {
		var ret string
		return ret
	}
	return *o.LogoUrl.Get()
}

// GetLogoUrlOk returns a tuple with the LogoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LegacyReportRequest) GetLogoUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogoUrl.Get(), o.LogoUrl.IsSet()
}

// HasLogoUrl returns a boolean if a field has been set.
func (o *LegacyReportRequest) HasLogoUrl() bool {
	if o != nil && o.LogoUrl.IsSet() {
		return true
	}

	return false
}

// SetLogoUrl gets a reference to the given NullableString and assigns it to the LogoUrl field.
func (o *LegacyReportRequest) SetLogoUrl(v string) {
	o.LogoUrl.Set(&v)
}
// SetLogoUrlNil sets the value for LogoUrl to be an explicit nil
func (o *LegacyReportRequest) SetLogoUrlNil() {
	o.LogoUrl.Set(nil)
}

// UnsetLogoUrl ensures that no value is present for LogoUrl, not even an explicit nil
func (o *LegacyReportRequest) UnsetLogoUrl() {
	o.LogoUrl.Unset()
}

// GetIncludeAppendix returns the IncludeAppendix field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LegacyReportRequest) GetIncludeAppendix() bool {
	if o == nil || IsNil(o.IncludeAppendix.Get()) {
		var ret bool
		return ret
	}
	return *o.IncludeAppendix.Get()
}

// GetIncludeAppendixOk returns a tuple with the IncludeAppendix field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LegacyReportRequest) GetIncludeAppendixOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IncludeAppendix.Get(), o.IncludeAppendix.IsSet()
}

// HasIncludeAppendix returns a boolean if a field has been set.
func (o *LegacyReportRequest) HasIncludeAppendix() bool {
	if o != nil && o.IncludeAppendix.IsSet() {
		return true
	}

	return false
}

// SetIncludeAppendix gets a reference to the given NullableBool and assigns it to the IncludeAppendix field.
func (o *LegacyReportRequest) SetIncludeAppendix(v bool) {
	o.IncludeAppendix.Set(&v)
}
// SetIncludeAppendixNil sets the value for IncludeAppendix to be an explicit nil
func (o *LegacyReportRequest) SetIncludeAppendixNil() {
	o.IncludeAppendix.Set(nil)
}

// UnsetIncludeAppendix ensures that no value is present for IncludeAppendix, not even an explicit nil
func (o *LegacyReportRequest) UnsetIncludeAppendix() {
	o.IncludeAppendix.Unset()
}

// GetAsknewsWatermark returns the AsknewsWatermark field value if set, zero value otherwise.
func (o *LegacyReportRequest) GetAsknewsWatermark() bool {
	if o == nil || IsNil(o.AsknewsWatermark) {
		var ret bool
		return ret
	}
	return *o.AsknewsWatermark
}

// GetAsknewsWatermarkOk returns a tuple with the AsknewsWatermark field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LegacyReportRequest) GetAsknewsWatermarkOk() (*bool, bool) {
	if o == nil || IsNil(o.AsknewsWatermark) {
		return nil, false
	}
	return o.AsknewsWatermark, true
}

// HasAsknewsWatermark returns a boolean if a field has been set.
func (o *LegacyReportRequest) HasAsknewsWatermark() bool {
	if o != nil && !IsNil(o.AsknewsWatermark) {
		return true
	}

	return false
}

// SetAsknewsWatermark gets a reference to the given bool and assigns it to the AsknewsWatermark field.
func (o *LegacyReportRequest) SetAsknewsWatermark(v bool) {
	o.AsknewsWatermark = &v
}

// GetIdentifier returns the Identifier field value if set, zero value otherwise.
func (o *LegacyReportRequest) GetIdentifier() string {
	if o == nil || IsNil(o.Identifier) {
		var ret string
		return ret
	}
	return *o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LegacyReportRequest) GetIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.Identifier) {
		return nil, false
	}
	return o.Identifier, true
}

// HasIdentifier returns a boolean if a field has been set.
func (o *LegacyReportRequest) HasIdentifier() bool {
	if o != nil && !IsNil(o.Identifier) {
		return true
	}

	return false
}

// SetIdentifier gets a reference to the given string and assigns it to the Identifier field.
func (o *LegacyReportRequest) SetIdentifier(v string) {
	o.Identifier = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *LegacyReportRequest) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LegacyReportRequest) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *LegacyReportRequest) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *LegacyReportRequest) SetModel(v string) {
	o.Model = &v
}

func (o LegacyReportRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LegacyReportRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Prompt != nil {
		toSerialize["prompt"] = o.Prompt
	}
	if o.LogoUrl.IsSet() {
		toSerialize["logo_url"] = o.LogoUrl.Get()
	}
	if o.IncludeAppendix.IsSet() {
		toSerialize["include_appendix"] = o.IncludeAppendix.Get()
	}
	if !IsNil(o.AsknewsWatermark) {
		toSerialize["asknews_watermark"] = o.AsknewsWatermark
	}
	if !IsNil(o.Identifier) {
		toSerialize["identifier"] = o.Identifier
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LegacyReportRequest) UnmarshalJSON(data []byte) (err error) {
	varLegacyReportRequest := _LegacyReportRequest{}

	err = json.Unmarshal(data, &varLegacyReportRequest)

	if err != nil {
		return err
	}

	*o = LegacyReportRequest(varLegacyReportRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "prompt")
		delete(additionalProperties, "logo_url")
		delete(additionalProperties, "include_appendix")
		delete(additionalProperties, "asknews_watermark")
		delete(additionalProperties, "identifier")
		delete(additionalProperties, "model")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLegacyReportRequest struct {
	value *LegacyReportRequest
	isSet bool
}

func (v NullableLegacyReportRequest) Get() *LegacyReportRequest {
	return v.value
}

func (v *NullableLegacyReportRequest) Set(val *LegacyReportRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLegacyReportRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLegacyReportRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLegacyReportRequest(val *LegacyReportRequest) *NullableLegacyReportRequest {
	return &NullableLegacyReportRequest{value: val, isSet: true}
}

func (v NullableLegacyReportRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLegacyReportRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


