/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.66
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ContentBlock1 - struct for ContentBlock1
type ContentBlock1 struct {
	AnthropicTextBlock *AnthropicTextBlock
	AnthropicThinkingBlock *AnthropicThinkingBlock
	AnthropicToolUseBlock *AnthropicToolUseBlock
}

// AnthropicTextBlockAsContentBlock1 is a convenience function that returns AnthropicTextBlock wrapped in ContentBlock1
func AnthropicTextBlockAsContentBlock1(v *AnthropicTextBlock) ContentBlock1 {
	return ContentBlock1{
		AnthropicTextBlock: v,
	}
}

// AnthropicThinkingBlockAsContentBlock1 is a convenience function that returns AnthropicThinkingBlock wrapped in ContentBlock1
func AnthropicThinkingBlockAsContentBlock1(v *AnthropicThinkingBlock) ContentBlock1 {
	return ContentBlock1{
		AnthropicThinkingBlock: v,
	}
}

// AnthropicToolUseBlockAsContentBlock1 is a convenience function that returns AnthropicToolUseBlock wrapped in ContentBlock1
func AnthropicToolUseBlockAsContentBlock1(v *AnthropicToolUseBlock) ContentBlock1 {
	return ContentBlock1{
		AnthropicToolUseBlock: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ContentBlock1) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AnthropicTextBlock
	err = newStrictDecoder(data).Decode(&dst.AnthropicTextBlock)
	if err == nil {
		jsonAnthropicTextBlock, _ := json.Marshal(dst.AnthropicTextBlock)
		if string(jsonAnthropicTextBlock) == "{}" { // empty struct
			dst.AnthropicTextBlock = nil
		} else {
			if err = validator.Validate(dst.AnthropicTextBlock); err != nil {
				dst.AnthropicTextBlock = nil
			} else {
				match++
			}
		}
	} else {
		dst.AnthropicTextBlock = nil
	}

	// try to unmarshal data into AnthropicThinkingBlock
	err = newStrictDecoder(data).Decode(&dst.AnthropicThinkingBlock)
	if err == nil {
		jsonAnthropicThinkingBlock, _ := json.Marshal(dst.AnthropicThinkingBlock)
		if string(jsonAnthropicThinkingBlock) == "{}" { // empty struct
			dst.AnthropicThinkingBlock = nil
		} else {
			if err = validator.Validate(dst.AnthropicThinkingBlock); err != nil {
				dst.AnthropicThinkingBlock = nil
			} else {
				match++
			}
		}
	} else {
		dst.AnthropicThinkingBlock = nil
	}

	// try to unmarshal data into AnthropicToolUseBlock
	err = newStrictDecoder(data).Decode(&dst.AnthropicToolUseBlock)
	if err == nil {
		jsonAnthropicToolUseBlock, _ := json.Marshal(dst.AnthropicToolUseBlock)
		if string(jsonAnthropicToolUseBlock) == "{}" { // empty struct
			dst.AnthropicToolUseBlock = nil
		} else {
			if err = validator.Validate(dst.AnthropicToolUseBlock); err != nil {
				dst.AnthropicToolUseBlock = nil
			} else {
				match++
			}
		}
	} else {
		dst.AnthropicToolUseBlock = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AnthropicTextBlock = nil
		dst.AnthropicThinkingBlock = nil
		dst.AnthropicToolUseBlock = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ContentBlock1)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ContentBlock1)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ContentBlock1) MarshalJSON() ([]byte, error) {
	if src.AnthropicTextBlock != nil {
		return json.Marshal(&src.AnthropicTextBlock)
	}

	if src.AnthropicThinkingBlock != nil {
		return json.Marshal(&src.AnthropicThinkingBlock)
	}

	if src.AnthropicToolUseBlock != nil {
		return json.Marshal(&src.AnthropicToolUseBlock)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ContentBlock1) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.AnthropicTextBlock != nil {
		return obj.AnthropicTextBlock
	}

	if obj.AnthropicThinkingBlock != nil {
		return obj.AnthropicThinkingBlock
	}

	if obj.AnthropicToolUseBlock != nil {
		return obj.AnthropicToolUseBlock
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ContentBlock1) GetActualInstanceValue() (interface{}) {
	if obj.AnthropicTextBlock != nil {
		return *obj.AnthropicTextBlock
	}

	if obj.AnthropicThinkingBlock != nil {
		return *obj.AnthropicThinkingBlock
	}

	if obj.AnthropicToolUseBlock != nil {
		return *obj.AnthropicToolUseBlock
	}

	// all schemas are nil
	return nil
}

type NullableContentBlock1 struct {
	value *ContentBlock1
	isSet bool
}

func (v NullableContentBlock1) Get() *ContentBlock1 {
	return v.value
}

func (v *NullableContentBlock1) Set(val *ContentBlock1) {
	v.value = val
	v.isSet = true
}

func (v NullableContentBlock1) IsSet() bool {
	return v.isSet
}

func (v *NullableContentBlock1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentBlock1(val *ContentBlock1) *NullableContentBlock1 {
	return &NullableContentBlock1{value: val, isSet: true}
}

func (v NullableContentBlock1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentBlock1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


