/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.28
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the UserProfileSubscription type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserProfileSubscription{}

// UserProfileSubscription struct for UserProfileSubscription
type UserProfileSubscription struct {
	Status string `json:"status"`
	Plan string `json:"plan"`
	PeriodStart NullableTime `json:"period_start,omitempty"`
	PeriodEnd NullableTime `json:"period_end,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UserProfileSubscription UserProfileSubscription

// NewUserProfileSubscription instantiates a new UserProfileSubscription object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserProfileSubscription(status string, plan string) *UserProfileSubscription {
	this := UserProfileSubscription{}
	this.Status = status
	this.Plan = plan
	return &this
}

// NewUserProfileSubscriptionWithDefaults instantiates a new UserProfileSubscription object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserProfileSubscriptionWithDefaults() *UserProfileSubscription {
	this := UserProfileSubscription{}
	return &this
}

// GetStatus returns the Status field value
func (o *UserProfileSubscription) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UserProfileSubscription) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UserProfileSubscription) SetStatus(v string) {
	o.Status = v
}

// GetPlan returns the Plan field value
func (o *UserProfileSubscription) GetPlan() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Plan
}

// GetPlanOk returns a tuple with the Plan field value
// and a boolean to check if the value has been set.
func (o *UserProfileSubscription) GetPlanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plan, true
}

// SetPlan sets field value
func (o *UserProfileSubscription) SetPlan(v string) {
	o.Plan = v
}

// GetPeriodStart returns the PeriodStart field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserProfileSubscription) GetPeriodStart() time.Time {
	if o == nil || IsNil(o.PeriodStart.Get()) {
		var ret time.Time
		return ret
	}
	return *o.PeriodStart.Get()
}

// GetPeriodStartOk returns a tuple with the PeriodStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserProfileSubscription) GetPeriodStartOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.PeriodStart.Get(), o.PeriodStart.IsSet()
}

// HasPeriodStart returns a boolean if a field has been set.
func (o *UserProfileSubscription) HasPeriodStart() bool {
	if o != nil && o.PeriodStart.IsSet() {
		return true
	}

	return false
}

// SetPeriodStart gets a reference to the given NullableTime and assigns it to the PeriodStart field.
func (o *UserProfileSubscription) SetPeriodStart(v time.Time) {
	o.PeriodStart.Set(&v)
}
// SetPeriodStartNil sets the value for PeriodStart to be an explicit nil
func (o *UserProfileSubscription) SetPeriodStartNil() {
	o.PeriodStart.Set(nil)
}

// UnsetPeriodStart ensures that no value is present for PeriodStart, not even an explicit nil
func (o *UserProfileSubscription) UnsetPeriodStart() {
	o.PeriodStart.Unset()
}

// GetPeriodEnd returns the PeriodEnd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserProfileSubscription) GetPeriodEnd() time.Time {
	if o == nil || IsNil(o.PeriodEnd.Get()) {
		var ret time.Time
		return ret
	}
	return *o.PeriodEnd.Get()
}

// GetPeriodEndOk returns a tuple with the PeriodEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserProfileSubscription) GetPeriodEndOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.PeriodEnd.Get(), o.PeriodEnd.IsSet()
}

// HasPeriodEnd returns a boolean if a field has been set.
func (o *UserProfileSubscription) HasPeriodEnd() bool {
	if o != nil && o.PeriodEnd.IsSet() {
		return true
	}

	return false
}

// SetPeriodEnd gets a reference to the given NullableTime and assigns it to the PeriodEnd field.
func (o *UserProfileSubscription) SetPeriodEnd(v time.Time) {
	o.PeriodEnd.Set(&v)
}
// SetPeriodEndNil sets the value for PeriodEnd to be an explicit nil
func (o *UserProfileSubscription) SetPeriodEndNil() {
	o.PeriodEnd.Set(nil)
}

// UnsetPeriodEnd ensures that no value is present for PeriodEnd, not even an explicit nil
func (o *UserProfileSubscription) UnsetPeriodEnd() {
	o.PeriodEnd.Unset()
}

func (o UserProfileSubscription) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserProfileSubscription) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["plan"] = o.Plan
	if o.PeriodStart.IsSet() {
		toSerialize["period_start"] = o.PeriodStart.Get()
	}
	if o.PeriodEnd.IsSet() {
		toSerialize["period_end"] = o.PeriodEnd.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UserProfileSubscription) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"plan",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserProfileSubscription := _UserProfileSubscription{}

	err = json.Unmarshal(data, &varUserProfileSubscription)

	if err != nil {
		return err
	}

	*o = UserProfileSubscription(varUserProfileSubscription)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "plan")
		delete(additionalProperties, "period_start")
		delete(additionalProperties, "period_end")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUserProfileSubscription struct {
	value *UserProfileSubscription
	isSet bool
}

func (v NullableUserProfileSubscription) Get() *UserProfileSubscription {
	return v.value
}

func (v *NullableUserProfileSubscription) Set(val *UserProfileSubscription) {
	v.value = val
	v.isSet = true
}

func (v NullableUserProfileSubscription) IsSet() bool {
	return v.isSet
}

func (v *NullableUserProfileSubscription) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserProfileSubscription(val *UserProfileSubscription) *NullableUserProfileSubscription {
	return &NullableUserProfileSubscription{value: val, isSet: true}
}

func (v NullableUserProfileSubscription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserProfileSubscription) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


