/*
AskNews API

AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)

API version: 0.24.28
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asknews

import (
	"encoding/json"
	"fmt"
)

// checks if the TopNArticlesForDomainItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TopNArticlesForDomainItem{}

// TopNArticlesForDomainItem struct for TopNArticlesForDomainItem
type TopNArticlesForDomainItem struct {
	ArticleUrl string `json:"article_url"`
	ArticleId NullableString `json:"article_id,omitempty"`
	HitCount int32 `json:"hit_count"`
	AdditionalProperties map[string]interface{}
}

type _TopNArticlesForDomainItem TopNArticlesForDomainItem

// NewTopNArticlesForDomainItem instantiates a new TopNArticlesForDomainItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTopNArticlesForDomainItem(articleUrl string, hitCount int32) *TopNArticlesForDomainItem {
	this := TopNArticlesForDomainItem{}
	this.ArticleUrl = articleUrl
	this.HitCount = hitCount
	return &this
}

// NewTopNArticlesForDomainItemWithDefaults instantiates a new TopNArticlesForDomainItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTopNArticlesForDomainItemWithDefaults() *TopNArticlesForDomainItem {
	this := TopNArticlesForDomainItem{}
	return &this
}

// GetArticleUrl returns the ArticleUrl field value
func (o *TopNArticlesForDomainItem) GetArticleUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ArticleUrl
}

// GetArticleUrlOk returns a tuple with the ArticleUrl field value
// and a boolean to check if the value has been set.
func (o *TopNArticlesForDomainItem) GetArticleUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArticleUrl, true
}

// SetArticleUrl sets field value
func (o *TopNArticlesForDomainItem) SetArticleUrl(v string) {
	o.ArticleUrl = v
}

// GetArticleId returns the ArticleId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TopNArticlesForDomainItem) GetArticleId() string {
	if o == nil || IsNil(o.ArticleId.Get()) {
		var ret string
		return ret
	}
	return *o.ArticleId.Get()
}

// GetArticleIdOk returns a tuple with the ArticleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TopNArticlesForDomainItem) GetArticleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ArticleId.Get(), o.ArticleId.IsSet()
}

// HasArticleId returns a boolean if a field has been set.
func (o *TopNArticlesForDomainItem) HasArticleId() bool {
	if o != nil && o.ArticleId.IsSet() {
		return true
	}

	return false
}

// SetArticleId gets a reference to the given NullableString and assigns it to the ArticleId field.
func (o *TopNArticlesForDomainItem) SetArticleId(v string) {
	o.ArticleId.Set(&v)
}
// SetArticleIdNil sets the value for ArticleId to be an explicit nil
func (o *TopNArticlesForDomainItem) SetArticleIdNil() {
	o.ArticleId.Set(nil)
}

// UnsetArticleId ensures that no value is present for ArticleId, not even an explicit nil
func (o *TopNArticlesForDomainItem) UnsetArticleId() {
	o.ArticleId.Unset()
}

// GetHitCount returns the HitCount field value
func (o *TopNArticlesForDomainItem) GetHitCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.HitCount
}

// GetHitCountOk returns a tuple with the HitCount field value
// and a boolean to check if the value has been set.
func (o *TopNArticlesForDomainItem) GetHitCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HitCount, true
}

// SetHitCount sets field value
func (o *TopNArticlesForDomainItem) SetHitCount(v int32) {
	o.HitCount = v
}

func (o TopNArticlesForDomainItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TopNArticlesForDomainItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["article_url"] = o.ArticleUrl
	if o.ArticleId.IsSet() {
		toSerialize["article_id"] = o.ArticleId.Get()
	}
	toSerialize["hit_count"] = o.HitCount

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TopNArticlesForDomainItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"article_url",
		"hit_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTopNArticlesForDomainItem := _TopNArticlesForDomainItem{}

	err = json.Unmarshal(data, &varTopNArticlesForDomainItem)

	if err != nil {
		return err
	}

	*o = TopNArticlesForDomainItem(varTopNArticlesForDomainItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "article_url")
		delete(additionalProperties, "article_id")
		delete(additionalProperties, "hit_count")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTopNArticlesForDomainItem struct {
	value *TopNArticlesForDomainItem
	isSet bool
}

func (v NullableTopNArticlesForDomainItem) Get() *TopNArticlesForDomainItem {
	return v.value
}

func (v *NullableTopNArticlesForDomainItem) Set(val *TopNArticlesForDomainItem) {
	v.value = val
	v.isSet = true
}

func (v NullableTopNArticlesForDomainItem) IsSet() bool {
	return v.isSet
}

func (v *NullableTopNArticlesForDomainItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTopNArticlesForDomainItem(val *TopNArticlesForDomainItem) *NullableTopNArticlesForDomainItem {
	return &NullableTopNArticlesForDomainItem{value: val, isSet: true}
}

func (v NullableTopNArticlesForDomainItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTopNArticlesForDomainItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


